project_id = "yxkgdalkbrriasiyyrwk"

[functions.tga-integration]
verify_jwt = false

[functions.tga-sync]
verify_jwt = false

[functions.tga-rto-import]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.generate-document]
verify_jwt = false

[functions.generate-excel-document]
verify_jwt = false
