import { test, expect } from "@playwright/test";

// Client persona (P0.8), using the "Demo RTO" test tenant -- a real client
// account, not staff impersonation ("View as Client" is explicitly not a
// substitute per the optimization plan's persona guidance). Storage state:
// playwright/.auth/client-demo.json, generated by `npm run e2e:auth-setup`.
// Read-only: navigation + assertions only.

test("Client home loads as an authenticated client, not staff shell", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (err) => errors.push(err.message));

  const response = await page.goto("/client/home");
  expect(response?.status()).toBeLessThan(400);
  await expect(page).not.toHaveURL(/\/login/);
  // ClientHomePage's time-aware greeting ("Good morning/afternoon/evening[, name]")
  // -- confirms this is really the client persona landing on real content,
  // not a staff/SA session that happened to also load something at this path.
  await expect(page.getByRole("heading", { name: /good (morning|afternoon|evening)/i, level: 1 })).toBeVisible();
  expect(errors).toEqual([]);
});

test("A SuperAdmin-only route denies the client persona", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (err) => errors.push(err.message));

  await page.goto("/admin/user-audit");
  await page.waitForLoadState("networkidle").catch(() => {});
  // ProtectedRoute's requireSuperAdmin bounces a non-SA session to /dashboard
  // (see src/components/ProtectedRoute.tsx) -- this must not render staff-only
  // admin content for a client session.
  await expect(page).not.toHaveURL(/\/admin\/user-audit/);
  expect(errors).toEqual([]);
});
