import { test, expect } from "@playwright/test";

// Super Admin persona (P0.8). Uses playwright/.auth/superadmin.json, a
// storage state generated by `npm run e2e:auth-setup` -- never logs in
// inside the test itself. Read-only by design: navigation + assertions
// only, no form submission, no destructive controls, no sign-out (signing
// out here would invalidate the storage state for every subsequent run).
//
// This persona's storage state belongs to a real production SuperAdmin
// account with full access -- keep this file's scope to reads only.

test("Dashboard loads as an authenticated SuperAdmin", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (err) => errors.push(err.message));

  const response = await page.goto("/dashboard");
  expect(response?.status()).toBeLessThan(400);
  await expect(page).not.toHaveURL(/\/login/);
  // MainDashboard's own data (client counts, activity feed, KPIs) can take
  // longer than the 5s assertion default on a cold Playwright context, even
  // though the heading itself renders quickly once auth resolves -- extend
  // the timeout rather than asserting on a fixed-size wait.
  await expect(page.getByRole("heading", { name: /welcome back/i })).toBeVisible({ timeout: 15_000 });
  expect(errors).toEqual([]);
});

test("A representative SuperAdmin-only route is reachable, not redirected to /dashboard", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (err) => errors.push(err.message));

  await page.goto("/settings/roles");
  await page.waitForLoadState("networkidle").catch(() => {});
  await expect(page).not.toHaveURL(/\/login/);
  await expect(page).not.toHaveURL("**/dashboard");
  expect(errors).toEqual([]);
});

// Legacy "Suggestion & Issue Register" -> "Support Tickets" redirects
// (src/App.tsx, "Suggestion & Issue Register (legacy -> redirect to Support
// Tickets)"). Characterization for the P1.1 dedup fix and for any future
// route-module extraction: these three legacy paths must keep landing on
// the single wrapped /support-tickets registration, not the removed
// unwrapped duplicate, and not each other's target by accident.

test("/suggestions redirects to /support-tickets (wrapped shell, not the removed duplicate)", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (err) => errors.push(err.message));

  await page.goto("/suggestions");
  await page.waitForURL("**/support-tickets");
  // Confirms the wrapped registration (SupportTicketsWrapper -> DashboardLayout),
  // not the formerly-duplicate unwrapped one -- the sidebar only renders inside
  // DashboardLayout. Scoped to <main>: the page title also appears as an h1 in
  // TopBar's banner, so an unscoped locator matches both.
  await expect(page.getByRole("main").getByRole("heading", { name: "Support Tickets", level: 1 })).toBeVisible();
  await expect(page.getByRole("navigation")).toBeVisible();
  expect(errors).toEqual([]);
});

test("/suggestions/new redirects to /support-tickets/new", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (err) => errors.push(err.message));

  await page.goto("/suggestions/new");
  await page.waitForURL("**/support-tickets/new");
  expect(errors).toEqual([]);
});

// Phase 4 P6-1 (Documents/generation): the create/edit dialog's Supabase
// mutation logic was extracted into useDocumentTemplateSave (src/features/
// document-templates/useDocumentTemplateSave.ts). This confirms the dialog
// still opens and wires to the extracted save function correctly -- no
// submission, no document created/edited/deleted, read-only by design.

test("Manage Documents: Create Document dialog opens on the browse step", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (err) => errors.push(err.message));

  await page.goto("/manage-documents");
  await expect(page).not.toHaveURL(/\/login/);
  await page.getByRole("button", { name: /create document/i }).click();
  await expect(page.getByRole("heading", { name: /select template file/i })).toBeVisible({ timeout: 10_000 });
  expect(errors).toEqual([]);
});

// Phase 4 P6-3 (Packages/time): the duplicated renewal-window calculation in
// RenewalConfirmDialog.tsx and ClientTimeTab.tsx's PackageBurndownCards was
// centralized into computeRenewalWindow (src/features/packages/
// renewalWindow.ts), fixing a real timezone bug in the process (see that
// file's doc comments). This confirms the Time tab's burn-down cards still
// render for a real tenant with an active package instance -- read-only,
// no time entry created/edited/deleted, no renewal actioned.

test("Client Time tab: package burn-down renders for a tenant with an active package", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (err) => errors.push(err.message));

  await page.goto("/tenant/7449?tab=time");
  await expect(page).not.toHaveURL(/\/login/);
  await expect(page.getByText(/package burn-?down/i).first()).toBeVisible({ timeout: 15_000 });
  expect(errors).toEqual([]);
});
