import { test, expect } from "@playwright/test";

// Super Admin persona (P0.8). Uses playwright/.auth/superadmin.json, a
// storage state generated by `npm run e2e:auth-setup` -- never logs in
// inside the test itself. Read-only by design: navigation + assertions
// only, no form submission, no destructive controls, no sign-out (signing
// out here would invalidate the storage state for every subsequent run).
//
// This persona's storage state belongs to a real production SuperAdmin
// account with full access -- keep this file's scope to reads only.

test("Dashboard loads as an authenticated SuperAdmin", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (err) => errors.push(err.message));

  const response = await page.goto("/dashboard");
  expect(response?.status()).toBeLessThan(400);
  await expect(page).not.toHaveURL(/\/login/);
  await expect(page.getByRole("heading", { name: /welcome back/i })).toBeVisible();
  expect(errors).toEqual([]);
});

test("A representative SuperAdmin-only route is reachable, not redirected to /dashboard", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (err) => errors.push(err.message));

  await page.goto("/settings/roles");
  await page.waitForLoadState("networkidle").catch(() => {});
  await expect(page).not.toHaveURL(/\/login/);
  await expect(page).not.toHaveURL("**/dashboard");
  expect(errors).toEqual([]);
});
