/**
 * PowerShell script generator — mirrors the "M365 Login" tab of
 * the Vivacity New User Setup workbook.
 *
 * Even though we auto-provision via the Graph API edge function,
 * this script is preserved as an audit/fallback artefact that admins
 * can copy-paste into a PowerShell prompt if Graph automation is
 * unavailable.
 */
export interface NewStarterInput {
  firstName: string;
  lastName: string;
  upn: string;            // e.g. firstname.lastname@vivacity.com.au
  mailNickname: string;   // e.g. firstname.lastname
  displayName: string;
  tempPassword: string;
  usageLocation: string;  // e.g. AU, PH
  m365Groups: string[];
  licenses: string[];
}

export function generatePowerShellScript(input: NewStarterInput): string {
  const groupAdds = input.m365Groups
    .map(
      (g) => `# Add to group "${g}"
$grp = Get-MgGroup -Filter "displayName eq '${g.replace(/'/g, "''")}'" -Top 1
if ($grp) { New-MgGroupMember -GroupId $grp.Id -DirectoryObjectId $newUser.Id }
else { Write-Warning "Group not found: ${g}" }`,
    )
    .join("\n\n");

  const licenseLines = input.licenses
    .map(
      (sku) => `# Assign license "${sku}"
$lic = Get-MgSubscribedSku -All | Where-Object { $_.SkuPartNumber -eq "${sku}" }
if ($lic) {
  Set-MgUserLicense -UserId $newUser.Id -AddLicenses @{ SkuId = $lic.SkuId } -RemoveLicenses @()
} else {
  Write-Warning "SKU not found: ${sku}"
}`,
    )
    .join("\n\n");

  return `# ──────────────────────────────────────────────────────────────
# Vivacity New Starter — Microsoft 365 setup
# Generated by Unicorn 2.0 (kept as audit/fallback)
# Run as: PowerShell (Administrator)
# ──────────────────────────────────────────────────────────────

# 1. Install Microsoft Graph module if not present
if (-not (Get-Module -ListAvailable -Name Microsoft.Graph)) {
  Install-Module Microsoft.Graph -Scope CurrentUser -Force
}

# 2. Connect with admin scopes
Connect-MgGraph -Scopes "User.ReadWrite.All","Group.ReadWrite.All","Directory.ReadWrite.All","Organization.Read.All" -NoWelcome

# 3. Create the user
$pwdProfile = @{
  Password = "${input.tempPassword.replace(/"/g, '`"')}"
  ForceChangePasswordNextSignIn = $true
}
$newUser = New-MgUser \`
  -AccountEnabled:$true \`
  -GivenName    "${input.firstName}" \`
  -Surname      "${input.lastName}" \`
  -DisplayName  "${input.displayName}" \`
  -MailNickname "${input.mailNickname}" \`
  -UserPrincipalName "${input.upn}" \`
  -UsageLocation "${input.usageLocation}" \`
  -PasswordProfile $pwdProfile

Write-Host "Created user $($newUser.UserPrincipalName) with id $($newUser.Id)"

# 4. Verify
Get-MgUser -UserId "${input.upn}" | Format-List Id, DisplayName, UserPrincipalName, AccountEnabled

# 5. Assign licenses
${licenseLines || "# (no licenses to assign)"}

# 6. Add to groups
${groupAdds || "# (no groups to add)"}

Write-Host "Setup complete for ${input.displayName}."
`;
}
