import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent } from '@/components/ui/card';
import { Info } from 'lucide-react';
import { PRIORITY_OPTIONS } from '@/types/auditWorkspace';

interface FindingFormValues {
  summary?: string;
  detail?: string | null;
  standard_reference?: string | null;
  regulatory_reference?: string | null;
  finding_code?: string | null;
  impact?: string | null;
  priority?: string;
}

interface AddFindingFormProps {
  auditId: string;
  sectionId?: string;
  responseId?: string;
  defaultSummary?: string;
  defaultPriority?: string;
  isAutoGenerated?: boolean;
  mode?: 'create' | 'edit';
  initialValues?: FindingFormValues;
  onSave: (finding: any) => void;
  onCancel: () => void;
}

export function AddFindingForm({
  auditId,
  sectionId,
  responseId,
  defaultSummary = '',
  defaultPriority = 'medium',
  isAutoGenerated = false,
  mode = 'create',
  initialValues,
  onSave,
  onCancel,
}: AddFindingFormProps) {
  const [summary, setSummary] = useState(initialValues?.summary ?? defaultSummary);
  const [detail, setDetail] = useState(initialValues?.detail ?? '');
  const [regulatoryRef, setRegulatoryRef] = useState(initialValues?.regulatory_reference ?? '');
  const [impact, setImpact] = useState(initialValues?.impact ?? '');
  const [priority, setPriority] = useState(initialValues?.priority ?? defaultPriority);

  const isEdit = mode === 'edit';
  const findingCode = initialValues?.finding_code || null;
  const legacyRef = initialValues?.standard_reference || null;

  const handleSave = () => {
    if (!summary.trim()) return;
    if (isEdit) {
      onSave({
        summary: summary.trim(),
        detail: detail.trim() || null,
        regulatory_reference: regulatoryRef.trim() || null,
        impact: impact.trim() || null,
        priority,
      });
    } else {
      // Do NOT include finding_code or standard_reference — DB trigger generates the code.
      onSave({
        audit_id: auditId,
        section_id: sectionId || null,
        response_id: responseId || null,
        summary: summary.trim(),
        detail: detail.trim() || null,
        regulatory_reference: regulatoryRef.trim() || null,
        impact: impact.trim() || null,
        priority,
        is_auto_generated: isAutoGenerated,
      });
    }
  };

  return (
    <Card className="border-amber-200 bg-amber-50/50">
      <CardContent className="p-4 space-y-3">
        {isEdit && findingCode && (
          <div className="flex items-center gap-2">
            <Label className="text-xs">Finding code</Label>
            <span className="font-mono font-bold text-sm px-2 py-0.5 rounded bg-background border">
              {findingCode}
            </span>
            <span className="text-[10px] text-muted-foreground">(auto-generated, read-only)</span>
          </div>
        )}
        {!isEdit && (
          <div className="flex items-start gap-2 rounded-md border bg-background/60 p-2 text-xs text-muted-foreground">
            <Info className="h-3.5 w-3.5 mt-0.5 flex-shrink-0" />
            <span>Finding code: will be auto-generated on save (e.g. <span className="font-mono">GOV-3</span>).</span>
          </div>
        )}
        <div>
          <Label className="text-xs">Summary *</Label>
          <Input value={summary} onChange={(e) => setSummary(e.target.value)} placeholder="Finding summary..." />
        </div>
        <div>
          <Label className="text-xs">Detail</Label>
          <Textarea value={detail || ''} onChange={(e) => setDetail(e.target.value)} rows={2} />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <Label className="text-xs">Regulatory Reference</Label>
            <Input
              value={regulatoryRef || ''}
              onChange={(e) => setRegulatoryRef(e.target.value)}
              placeholder="e.g. Std 1.1, NC 7.2, ESOS s.22"
            />
            <p className="text-[10px] text-muted-foreground mt-1">
              SRTO 2025 clause, National Code 2018 Standard, or ESOS section.
            </p>
          </div>
          <div>
            <Label className="text-xs">Priority</Label>
            <Select value={priority} onValueChange={setPriority}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {PRIORITY_OPTIONS.map(o => (
                  <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
        <div>
          <Label className="text-xs">Impact</Label>
          <Textarea value={impact || ''} onChange={(e) => setImpact(e.target.value)} rows={2} />
        </div>
        {isEdit && legacyRef && (
          <div>
            <Label className="text-xs">Legacy reference (read-only)</Label>
            <p className="text-xs text-muted-foreground italic px-2 py-1 bg-muted/50 rounded">{legacyRef}</p>
          </div>
        )}
        <div className="flex gap-2">
          <Button size="sm" onClick={handleSave} disabled={!summary.trim()}>
            {isEdit ? 'Update Finding' : 'Save Finding'}
          </Button>
          <Button size="sm" variant="outline" onClick={onCancel}>Cancel</Button>
        </div>
      </CardContent>
    </Card>
  );
}
