import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent } from '@/components/ui/card';
import { PRIORITY_OPTIONS } from '@/types/auditWorkspace';

interface FindingFormValues {
  summary?: string;
  detail?: string | null;
  standard_reference?: string | null;
  impact?: string | null;
  priority?: string;
}

interface AddFindingFormProps {
  auditId: string;
  sectionId?: string;
  responseId?: string;
  defaultSummary?: string;
  defaultStandardRef?: string;
  defaultPriority?: string;
  isAutoGenerated?: boolean;
  mode?: 'create' | 'edit';
  initialValues?: FindingFormValues;
  onSave: (finding: any) => void;
  onCancel: () => void;
}

export function AddFindingForm({
  auditId,
  sectionId,
  responseId,
  defaultSummary = '',
  defaultStandardRef = '',
  defaultPriority = 'medium',
  isAutoGenerated = false,
  mode = 'create',
  initialValues,
  onSave,
  onCancel,
}: AddFindingFormProps) {
  const [summary, setSummary] = useState(initialValues?.summary ?? defaultSummary);
  const [detail, setDetail] = useState(initialValues?.detail ?? '');
  const [standardRef, setStandardRef] = useState(initialValues?.standard_reference ?? defaultStandardRef);
  const [impact, setImpact] = useState(initialValues?.impact ?? '');
  const [priority, setPriority] = useState(initialValues?.priority ?? defaultPriority);

  const isEdit = mode === 'edit';

  const handleSave = () => {
    if (!summary.trim()) return;
    if (isEdit) {
      onSave({
        summary: summary.trim(),
        detail: detail.trim() || null,
        standard_reference: standardRef.trim() || null,
        impact: impact.trim() || null,
        priority,
      });
    } else {
      onSave({
        audit_id: auditId,
        section_id: sectionId || null,
        response_id: responseId || null,
        summary: summary.trim(),
        detail: detail.trim() || null,
        standard_reference: standardRef.trim() || null,
        impact: impact.trim() || null,
        priority,
        is_auto_generated: isAutoGenerated,
      });
    }
  };

  return (
    <Card className="border-amber-200 bg-amber-50/50">
      <CardContent className="p-4 space-y-3">
        <div>
          <Label className="text-xs">Summary *</Label>
          <Input value={summary} onChange={(e) => setSummary(e.target.value)} placeholder="Finding summary..." />
        </div>
        <div>
          <Label className="text-xs">Detail</Label>
          <Textarea value={detail || ''} onChange={(e) => setDetail(e.target.value)} rows={2} />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <Label className="text-xs">Standard Reference</Label>
            <Input value={standardRef || ''} onChange={(e) => setStandardRef(e.target.value)} placeholder="e.g. Standard 1.3(b)" />
          </div>
          <div>
            <Label className="text-xs">Priority</Label>
            <Select value={priority} onValueChange={setPriority}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {PRIORITY_OPTIONS.map(o => (
                  <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
        <div>
          <Label className="text-xs">Impact</Label>
          <Textarea value={impact || ''} onChange={(e) => setImpact(e.target.value)} rows={2} />
        </div>
        <div className="flex gap-2">
          <Button size="sm" onClick={handleSave} disabled={!summary.trim()}>
            {isEdit ? 'Update Finding' : 'Save Finding'}
          </Button>
          <Button size="sm" variant="outline" onClick={onCancel}>Cancel</Button>
        </div>
      </CardContent>
    </Card>
  );
}
