import { useState, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

interface ExcelGenerationOptions {
  documentId: number;
  tenantId: number;
  clientLegacyId?: string;
  stageId?: number;
  packageId?: number;
  mode?: 'single' | 'pack';
}

interface GenerationResult {
  success: boolean;
  downloadUrl?: string;
  fileName?: string;
  generatedDocumentId?: string;
  error?: string;
}

export function useExcelGeneration() {
  const [generating, setGenerating] = useState(false);
  const [generatingDocId, setGeneratingDocId] = useState<number | null>(null);
  const { toast } = useToast();

  const generateExcelDocument = useCallback(async (
    options: ExcelGenerationOptions
  ): Promise<GenerationResult> => {
    const { documentId, tenantId, clientLegacyId, stageId, packageId, mode = 'single' } = options;
    
    setGenerating(true);
    setGeneratingDocId(documentId);

    try {
      const { data: sessionData } = await supabase.auth.getSession();
      if (!sessionData.session) {
        throw new Error('Not authenticated');
      }

      const response = await supabase.functions.invoke('generate-excel-document', {
        body: {
          document_id: documentId,
          tenant_id: tenantId,
          client_legacy_id: clientLegacyId,
          stage_id: stageId,
          package_id: packageId,
          mode
        }
      });

      if (response.error) {
        throw new Error(response.error.message || 'Generation failed');
      }

      const data = response.data;
      
      if (!data.success) {
        throw new Error(data.error || 'Generation failed');
      }

      toast({
        title: 'Document Generated',
        description: `Excel document "${data.file_name}" is ready for download.`
      });

      return {
        success: true,
        downloadUrl: data.download_url,
        fileName: data.file_name,
        generatedDocumentId: data.generated_document?.id
      };
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Failed to generate Excel document';
      
      toast({
        title: 'Generation Failed',
        description: errorMessage,
        variant: 'destructive'
      });

      return {
        success: false,
        error: errorMessage
      };
    } finally {
      setGenerating(false);
      setGeneratingDocId(null);
    }
  }, [toast]);

  const generateAndDownload = useCallback(async (options: ExcelGenerationOptions) => {
    const result = await generateExcelDocument(options);
    
    if (result.success && result.downloadUrl) {
      // Trigger download
      const link = document.createElement('a');
      link.href = result.downloadUrl;
      link.download = result.fileName || 'document.xlsx';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }

    return result;
  }, [generateExcelDocument]);

  const isDocumentGenerating = useCallback((docId: number) => {
    return generating && generatingDocId === docId;
  }, [generating, generatingDocId]);

  return {
    generating,
    generatingDocId,
    generateExcelDocument,
    generateAndDownload,
    isDocumentGenerating
  };
}

// Helper to check if a document is an Excel file
export function isExcelDocument(format: string | null | undefined): boolean {
  if (!format) return false;
  const excelFormats = ['xlsx', 'xls', 'xlsm', 'xlsb'];
  return excelFormats.includes(format.toLowerCase());
}

// Helper to check if a document supports auto-generation
export function supportsAutoGeneration(
  format: string | null | undefined,
  isAutoGenerated: boolean | null | undefined
): boolean {
  if (!isAutoGenerated) return false;
  if (!format) return false;
  
  const supportedFormats = ['docx', 'xlsx', 'xls', 'xlsm'];
  return supportedFormats.includes(format.toLowerCase());
}
