import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

export interface TokenInfo {
  token: string;
  sheet: string;
  cell: string;
  context: 'cell' | 'header_footer' | 'named_range' | 'shape' | 'unknown';
  sample_text: string;
  format: 'double_brace' | 'double_angle' | 'double_bracket' | 'mergefield';
}

export interface DropdownInfo {
  dropdown_id: string;
  sheet: string;
  cell: string;
  validation_type: 'list';
  source_type: 'inline' | 'range' | 'named_range';
  source_ref: string;
  resolved_range: string | null;
  row_count_estimate: number | null;
  original_values: string[] | null;
}

export interface TokenBinding {
  source_type: 'client' | 'tenant' | 'package' | 'stage' | 'system' | 'static';
  source_field?: string;
  static_value?: string;
  preview_value?: string;
}

export interface DropdownBinding {
  list_id: string;
  list_name?: string;
}

export interface ExcelBinding {
  id: string;
  document_id: number;
  binding_version: number;
  status: 'draft' | 'ready' | 'error';
  detected_tokens: TokenInfo[];
  detected_dropdowns: DropdownInfo[];
  token_bindings: Record<string, TokenBinding>;
  dropdown_bindings: Record<string, DropdownBinding>;
  last_validated_at: string | null;
  validation_errors: ValidationError[];
  created_at: string;
  updated_at: string;
}

export interface ValidationError {
  type: 'unbound_token' | 'unbound_dropdown' | 'empty_list' | 'no_bindings';
  token?: string;
  dropdown_id?: string;
  location?: string;
  message: string;
}

export interface LookupList {
  id: string;
  tenant_id: number | null;
  key: string;
  name: string;
  description: string | null;
  created_at: string;
  items?: LookupListItem[];
}

export interface LookupListItem {
  id: string;
  list_id: string;
  value: string;
  label: string | null;
  sort_order: number;
  is_active: boolean;
}

// Available merge field sources
export const MERGE_FIELD_SOURCES = [
  { type: 'client' as const, label: 'Client Field', fields: [
    { key: 'companyname', label: 'Company Name' },
    { key: 'contactname', label: 'Contact Name' },
    { key: 'email', label: 'Email' },
    { key: 'phone', label: 'Phone' },
    { key: 'abn', label: 'ABN' },
    { key: 'rtoid', label: 'RTO ID' },
    { key: 'rto_name', label: 'RTO Name' },
    { key: 'address', label: 'Address' },
    { key: 'suburb', label: 'Suburb' },
    { key: 'state', label: 'State' },
    { key: 'postcode', label: 'Postcode' },
    { key: 'website', label: 'Website' },
  ]},
  { type: 'tenant' as const, label: 'Tenant/Org Field', fields: [
    { key: 'name', label: 'Tenant Name' },
    { key: 'code', label: 'Tenant Code' },
  ]},
  { type: 'system' as const, label: 'System', fields: [
    { key: 'current_date', label: 'Current Date' },
    { key: 'current_time', label: 'Current Time' },
    { key: 'current_year', label: 'Current Year' },
    { key: 'generated_by', label: 'Generated By (User)' },
  ]},
  { type: 'static' as const, label: 'Static Value', fields: [] },
];

export function useExcelBindings(documentId: number | null) {
  const [binding, setBinding] = useState<ExcelBinding | null>(null);
  const [lookupLists, setLookupLists] = useState<LookupList[]>([]);
  const [loading, setLoading] = useState(false);
  const [scanning, setScanning] = useState(false);
  const [validating, setValidating] = useState(false);
  const { toast } = useToast();

  const fetchBinding = useCallback(async () => {
    if (!documentId) return;
    
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('excel_template_bindings')
        .select('*')
        .eq('document_id', documentId)
        .maybeSingle();
      
      if (error) throw error;
      
      if (data) {
        setBinding({
          ...data,
          detected_tokens: (data.detected_tokens || []) as unknown as TokenInfo[],
          detected_dropdowns: (data.detected_dropdowns || []) as unknown as DropdownInfo[],
          token_bindings: (data.token_bindings || {}) as unknown as Record<string, TokenBinding>,
          dropdown_bindings: (data.dropdown_bindings || {}) as unknown as Record<string, DropdownBinding>,
          validation_errors: (data.validation_errors || []) as unknown as ValidationError[],
        } as ExcelBinding);
      } else {
        setBinding(null);
      }
    } catch (error: any) {
      console.error('Error fetching excel bindings:', error);
    } finally {
      setLoading(false);
    }
  }, [documentId]);

  const fetchLookupLists = useCallback(async () => {
    try {
      const { data, error } = await supabase
        .from('lookup_lists')
        .select(`
          *,
          items:lookup_list_items(*)
        `)
        .order('name');
      
      if (error) throw error;
      setLookupLists((data || []) as LookupList[]);
    } catch (error: any) {
      console.error('Error fetching lookup lists:', error);
    }
  }, []);

  useEffect(() => {
    fetchBinding();
    fetchLookupLists();
  }, [fetchBinding, fetchLookupLists]);

  const scanDocument = useCallback(async () => {
    if (!documentId) return null;
    
    setScanning(true);
    try {
      const { data: sessionData } = await supabase.auth.getSession();
      if (!sessionData.session) throw new Error('Not authenticated');

      const { data, error } = await supabase.functions.invoke('scan-document', {
        body: { document_id: documentId }
      });

      if (error) throw error;
      if (!data.success) throw new Error(data.error || 'Scan failed');

      toast({
        title: 'Document Scanned',
        description: `Found ${data.merge_fields?.length || 0} tokens and ${data.dropdowns?.length || 0} dropdowns`
      });

      await fetchBinding();
      return data;
    } catch (error: any) {
      toast({
        title: 'Scan Failed',
        description: error.message,
        variant: 'destructive'
      });
      return null;
    } finally {
      setScanning(false);
    }
  }, [documentId, toast, fetchBinding]);

  const updateTokenBinding = useCallback(async (token: string, binding: TokenBinding) => {
    if (!documentId || !binding) return;

    try {
      const currentBindings = await supabase
        .from('excel_template_bindings')
        .select('token_bindings')
        .eq('document_id', documentId)
        .single();

      if (currentBindings.error) throw currentBindings.error;

      const updatedBindings = {
        ...(currentBindings.data.token_bindings as Record<string, unknown> || {}),
        [token]: binding
      };

      const { error } = await supabase
        .from('excel_template_bindings')
        .update({ 
          token_bindings: updatedBindings as unknown as Record<string, never>,
          status: 'draft'
        })
        .eq('document_id', documentId);

      if (error) throw error;

      await fetchBinding();
      toast({ title: 'Token binding updated' });
    } catch (error: any) {
      toast({
        title: 'Update failed',
        description: error.message,
        variant: 'destructive'
      });
    }
  }, [documentId, toast, fetchBinding]);

  const updateDropdownBinding = useCallback(async (dropdownId: string, listId: string, listName: string) => {
    if (!documentId) return;

    try {
      const currentBindings = await supabase
        .from('excel_template_bindings')
        .select('dropdown_bindings')
        .eq('document_id', documentId)
        .single();

      if (currentBindings.error) throw currentBindings.error;

      const updatedBindings = {
        ...(currentBindings.data.dropdown_bindings as Record<string, unknown> || {}),
        [dropdownId]: { list_id: listId, list_name: listName }
      };

      const { error } = await supabase
        .from('excel_template_bindings')
        .update({ 
          dropdown_bindings: updatedBindings as unknown as Record<string, never>,
          status: 'draft'
        })
        .eq('document_id', documentId);

      if (error) throw error;

      await fetchBinding();
      toast({ title: 'Dropdown binding updated' });
    } catch (error: any) {
      toast({
        title: 'Update failed',
        description: error.message,
        variant: 'destructive'
      });
    }
  }, [documentId, toast, fetchBinding]);

  const validateBindings = useCallback(async () => {
    if (!documentId) return null;

    setValidating(true);
    try {
      const { data, error } = await supabase.rpc('validate_excel_bindings', {
        p_document_id: documentId
      });

      if (error) throw error;

      const result = data as unknown as { success: boolean; errors: ValidationError[]; status: string };
      
      await fetchBinding();

      if (result.success) {
        toast({
          title: 'Validation Passed',
          description: 'All bindings are configured correctly'
        });
      } else {
        toast({
          title: 'Validation Issues',
          description: `Found ${result.errors.length} issue(s) that need attention`,
          variant: 'destructive'
        });
      }

      return result;
    } catch (error: any) {
      toast({
        title: 'Validation failed',
        description: error.message,
        variant: 'destructive'
      });
      return null;
    } finally {
      setValidating(false);
    }
  }, [documentId, toast, fetchBinding]);

  const createLookupList = useCallback(async (
    key: string,
    name: string,
    items: string[],
    tenantId?: number
  ) => {
    try {
      // Create the list
      const { data: list, error: listError } = await supabase
        .from('lookup_lists')
        .insert({
          key,
          name,
          tenant_id: tenantId || null
        })
        .select()
        .single();

      if (listError) throw listError;

      // Add items
      if (items.length > 0) {
        const itemRecords = items.map((value, index) => ({
          list_id: list.id,
          value,
          sort_order: index
        }));

        const { error: itemsError } = await supabase
          .from('lookup_list_items')
          .insert(itemRecords);

        if (itemsError) throw itemsError;
      }

      await fetchLookupLists();
      toast({ title: 'Lookup list created' });
      return list as LookupList;
    } catch (error: any) {
      toast({
        title: 'Failed to create list',
        description: error.message,
        variant: 'destructive'
      });
      return null;
    }
  }, [toast, fetchLookupLists]);

  const addListItems = useCallback(async (listId: string, items: string[]) => {
    try {
      const { data: existingItems } = await supabase
        .from('lookup_list_items')
        .select('sort_order')
        .eq('list_id', listId)
        .order('sort_order', { ascending: false })
        .limit(1);

      const startOrder = (existingItems?.[0]?.sort_order || -1) + 1;

      const itemRecords = items.map((value, index) => ({
        list_id: listId,
        value,
        sort_order: startOrder + index
      }));

      const { error } = await supabase
        .from('lookup_list_items')
        .insert(itemRecords);

      if (error) throw error;

      await fetchLookupLists();
      toast({ title: 'Items added' });
    } catch (error: any) {
      toast({
        title: 'Failed to add items',
        description: error.message,
        variant: 'destructive'
      });
    }
  }, [toast, fetchLookupLists]);

  return {
    binding,
    lookupLists,
    loading,
    scanning,
    validating,
    scanDocument,
    updateTokenBinding,
    updateDropdownBinding,
    validateBindings,
    createLookupList,
    addListItems,
    refresh: fetchBinding,
    refreshLists: fetchLookupLists
  };
}

// Helper to check binding status for a document
export function useExcelBindingStatus(documentId: number | null) {
  const [status, setStatus] = useState<'none' | 'draft' | 'ready' | 'error'>('none');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!documentId) {
      setStatus('none');
      return;
    }

    const fetchStatus = async () => {
      setLoading(true);
      try {
        const { data, error } = await supabase
          .from('excel_template_bindings')
          .select('status')
          .eq('document_id', documentId)
          .maybeSingle();

        if (error) throw error;
        const s = data?.status as 'draft' | 'ready' | 'error' | undefined;
        setStatus(s || 'none');
      } catch {
        setStatus('none');
      } finally {
        setLoading(false);
      }
    };

    fetchStatus();
  }, [documentId]);

  return { status, loading };
}
