import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

interface MinutesContent {
  meeting_title: string;
  meeting_date: string;
  meeting_time: string;
  duration_minutes: number;
  attendees: string[];
  apologies: string[];
  agenda_items: string[];
  discussion_notes: string;
  decisions: string[];
  actions: Array<{ action: string; owner: string; due_date: string }>;
  next_meeting: string;
}

function generatePdfHtml(content: MinutesContent, title: string, tenantName: string): string {
  const actionsTable = content.actions?.length > 0
    ? `<table style="width:100%;border-collapse:collapse;margin-top:8px;">
        <thead>
          <tr style="background:#f3f4f6;">
            <th style="text-align:left;padding:6px 8px;border:1px solid #e5e7eb;font-size:12px;">Action</th>
            <th style="text-align:left;padding:6px 8px;border:1px solid #e5e7eb;font-size:12px;width:120px;">Owner</th>
            <th style="text-align:left;padding:6px 8px;border:1px solid #e5e7eb;font-size:12px;width:100px;">Due Date</th>
          </tr>
        </thead>
        <tbody>
          ${content.actions.map(a => `
            <tr>
              <td style="padding:6px 8px;border:1px solid #e5e7eb;font-size:12px;">${escapeHtml(a.action)}</td>
              <td style="padding:6px 8px;border:1px solid #e5e7eb;font-size:12px;">${escapeHtml(a.owner)}</td>
              <td style="padding:6px 8px;border:1px solid #e5e7eb;font-size:12px;">${escapeHtml(a.due_date)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>`
    : '';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: Arial, Helvetica, sans-serif; margin: 40px; color: #1f2937; line-height: 1.5; }
    h1 { font-size: 20px; margin-bottom: 4px; color: #111827; }
    h2 { font-size: 14px; color: #6b7280; margin-top: 24px; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
    .meta { font-size: 12px; color: #6b7280; margin-bottom: 4px; }
    .tenant { font-size: 14px; color: #4b5563; margin-bottom: 16px; }
    ul { padding-left: 20px; }
    li { font-size: 13px; margin-bottom: 4px; }
    .notes { font-size: 13px; white-space: pre-wrap; background: #f9fafb; padding: 12px; border-radius: 4px; }
    .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 12px; }
  </style>
</head>
<body>
  <div class="tenant">${escapeHtml(tenantName)}</div>
  <h1>${escapeHtml(title)}</h1>
  <div class="meta">${escapeHtml(content.meeting_date)}${content.meeting_time ? ' at ' + escapeHtml(content.meeting_time) : ''}${content.duration_minutes > 0 ? ' (' + content.duration_minutes + ' minutes)' : ''}</div>

  ${content.attendees?.length > 0 ? `
    <h2>Attendees</h2>
    <p style="font-size:13px;">${content.attendees.map(escapeHtml).join(', ')}</p>
  ` : ''}

  ${content.apologies?.length > 0 ? `
    <h2>Apologies</h2>
    <p style="font-size:13px;">${content.apologies.map(escapeHtml).join(', ')}</p>
  ` : ''}

  ${content.agenda_items?.length > 0 ? `
    <h2>Agenda</h2>
    <ul>${content.agenda_items.map(i => `<li>${escapeHtml(i)}</li>`).join('')}</ul>
  ` : ''}

  ${content.discussion_notes ? `
    <h2>Discussion Notes</h2>
    <div class="notes">${escapeHtml(content.discussion_notes)}</div>
  ` : ''}

  ${content.decisions?.length > 0 ? `
    <h2>Decisions</h2>
    <ul>${content.decisions.map(d => `<li>${escapeHtml(d)}</li>`).join('')}</ul>
  ` : ''}

  ${content.actions?.length > 0 ? `
    <h2>Action Items</h2>
    ${actionsTable}
  ` : ''}

  ${content.next_meeting ? `
    <h2>Next Meeting</h2>
    <p style="font-size:13px;">${escapeHtml(content.next_meeting)}</p>
  ` : ''}

  <div class="footer">
    Generated by Unicorn 2.0 · ${new Date().toISOString().split('T')[0]}
  </div>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return (str || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: 'Missing authorization header' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const body = await req.json();
    const minutesId: string = body?.minutes_id;

    if (!minutesId) {
      return new Response(
        JSON.stringify({ error: 'minutes_id is required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Authenticate user
    const { data: { user }, error: authError } = await supabaseAdmin.auth.getUser(
      authHeader.replace('Bearer ', '')
    );

    if (authError || !user) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Verify Vivacity team
    const { data: userRecord } = await supabaseAdmin
      .from('users')
      .select('is_vivacity_internal, first_name, last_name')
      .eq('user_uuid', user.id)
      .single();

    if (!userRecord?.is_vivacity_internal) {
      return new Response(
        JSON.stringify({ error: 'Only Vivacity team can publish minutes' }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Get the minutes record
    const { data: minutes, error: minutesError } = await supabaseAdmin
      .from('meeting_minutes')
      .select('*')
      .eq('id', minutesId)
      .single();

    if (minutesError || !minutes) {
      return new Response(
        JSON.stringify({ error: 'Minutes not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (minutes.status === 'published') {
      return new Response(
        JSON.stringify({ error: 'Minutes already published' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const content = minutes.content as MinutesContent;

    // Validate minimum fields
    if (!content.attendees?.length || (!content.decisions?.length && !content.actions?.length && !content.discussion_notes)) {
      return new Response(
        JSON.stringify({ error: 'Minutes must have attendees and at least one of: decisions, actions, or discussion notes' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Get tenant name
    const { data: tenant } = await supabaseAdmin
      .from('tenants')
      .select('name')
      .eq('id', minutes.tenant_id)
      .single();

    const tenantName = tenant?.name || 'Client';

    // Get meeting details
    const { data: meeting } = await supabaseAdmin
      .from('meetings')
      .select('title, starts_at, client_id')
      .eq('id', minutes.meeting_id)
      .single();

    // Generate HTML content for PDF
    const htmlContent = generatePdfHtml(content, minutes.title, tenantName);

    // Store the HTML as a file in storage for the portal
    const fileName = `${minutes.title.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '-')}.html`;
    const storagePath = `meeting-minutes/${minutes.tenant_id}/${minutes.meeting_id}/${fileName}`;

    const { error: storageError } = await supabaseAdmin.storage
      .from('documents')
      .upload(storagePath, new TextEncoder().encode(htmlContent), {
        contentType: 'text/html',
        upsert: true,
      });

    if (storageError) {
      console.error('[publish-minutes] Storage upload failed:', storageError);
      // Continue without storage - create portal doc anyway
    }

    // Create portal document
    const publisherName = [userRecord.first_name, userRecord.last_name].filter(Boolean).join(' ') || 'Vivacity Team';

    const { data: portalDoc, error: portalError } = await supabaseAdmin
      .from('portal_documents')
      .insert({
        tenant_id: minutes.tenant_id,
        file_name: fileName,
        file_type: 'text/html',
        file_size: new TextEncoder().encode(htmlContent).length,
        description: `Meeting minutes published by ${publisherName}`,
        uploaded_by: user.id,
        direction: 'outbound',
        is_client_visible: true,
        storage_path: storageError ? null : storagePath,
      })
      .select('id')
      .single();

    if (portalError) {
      console.error('[publish-minutes] Portal doc creation failed:', portalError);
      return new Response(
        JSON.stringify({ error: 'Failed to create portal document' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Update minutes status
    const now = new Date().toISOString();
    await supabaseAdmin.from('meeting_minutes').update({
      status: 'published',
      published_at: now,
      published_by: user.id,
      pdf_document_id: portalDoc.id,
      pdf_storage_path: storageError ? null : storagePath,
      updated_at: now,
    }).eq('id', minutesId);

    // Audit log
    await supabaseAdmin.from('audit_events').insert({
      entity: 'meeting_minutes',
      entity_id: minutesId,
      action: 'minutes_published',
      user_id: user.id,
      details: {
        meeting_id: minutes.meeting_id,
        portal_document_id: portalDoc.id,
        tenant_id: minutes.tenant_id,
        title: minutes.title,
        tenant_name: tenantName,
      },
    });

    console.log('[publish-minutes] Published:', { minutesId, portalDocId: portalDoc.id });

    return new Response(
      JSON.stringify({
        success: true,
        minutes_id: minutesId,
        portal_document_id: portalDoc.id,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('[publish-minutes] Error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
