import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface RequestBody {
  tenant_id: number;
  client_id: number;
  client_name: string;
  from_date: string;
  to_date: string;
  event_types?: string[] | null;
}

Deno.serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Verify user
    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    if (authError || !user) {
      console.error('Auth error:', authError);
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const body: RequestBody = await req.json();
    const { tenant_id, client_id, client_name, from_date, to_date, event_types } = body;

    console.log(`Exporting timeline PDF for client ${client_id}, tenant ${tenant_id}`);
    console.log(`Date range: ${from_date} to ${to_date}`);
    console.log(`Event types: ${event_types?.join(', ') || 'all'}`);

    // Verify user has access to this tenant
    const { data: userRecord, error: userError } = await supabase
      .from('users')
      .select('tenant_id, role')
      .eq('user_uuid', user.id)
      .single();

    if (userError || !userRecord) {
      console.error('User record error:', userError);
      return new Response(JSON.stringify({ error: 'User not found' }), {
        status: 403,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // SuperAdmin can access any tenant, others must match
    if (userRecord.role !== 'SuperAdmin' && userRecord.tenant_id !== tenant_id) {
      return new Response(JSON.stringify({ error: 'Access denied' }), {
        status: 403,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // Fetch timeline data using the export RPC
    const { data: events, error: fetchError } = await supabase.rpc('rpc_export_client_timeline', {
      p_tenant_id: tenant_id,
      p_client_id: client_id,
      p_from_date: from_date,
      p_to_date: to_date,
      p_event_types: event_types
    });

    if (fetchError) {
      console.error('Fetch error:', fetchError);
      return new Response(JSON.stringify({ error: 'Failed to fetch timeline data' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    console.log(`Found ${events?.length || 0} events`);

    // Get user's name for "generated by"
    const { data: generatorUser } = await supabase
      .from('users')
      .select('first_name, last_name')
      .eq('user_uuid', user.id)
      .single();

    const generatedBy = generatorUser 
      ? `${generatorUser.first_name} ${generatorUser.last_name}`
      : user.email || 'Unknown';

    // Generate PDF content
    const pdfContent = generatePDF({
      clientName: client_name,
      fromDate: from_date,
      toDate: to_date,
      generatedAt: new Date().toISOString(),
      generatedBy,
      events: events || [],
      eventTypes: event_types
    });

    return new Response(JSON.stringify({ pdf: pdfContent }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error('Export error:', error);
    return new Response(JSON.stringify({ error: errorMessage }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});

interface PDFData {
  clientName: string;
  fromDate: string;
  toDate: string;
  generatedAt: string;
  generatedBy: string;
  events: any[];
  eventTypes?: string[] | null;
}

function generatePDF(data: PDFData): string {
  // Simple PDF generation using raw PDF structure
  // This creates a basic but functional PDF document
  
  const formatDate = (dateStr: string) => {
    try {
      return new Date(dateStr).toLocaleDateString('en-AU', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });
    } catch {
      return dateStr;
    }
  };

  const formatEventType = (type: string) => {
    return type.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  };

  const escapeText = (text: string) => {
    return (text || '')
      .replace(/\\/g, '\\\\')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)')
      .replace(/[\r\n]+/g, ' ')
      .substring(0, 200);
  };

  // Group events by type
  const eventsByType = data.events.reduce((acc: Record<string, any[]>, event: any) => {
    const type = event.event_type as string;
    if (!acc[type]) acc[type] = [];
    acc[type].push(event);
    return acc;
  }, {} as Record<string, any[]>);

  // Build PDF content
  let yPos = 750;
  const lineHeight = 14;
  const pageWidth = 595;
  const margin = 50;
  const contentWidth = pageWidth - margin * 2;
  
  let streamContent = '';
  
  // Title
  streamContent += `BT /F1 18 Tf ${margin} ${yPos} Td (Client Timeline Audit Report) Tj ET\n`;
  yPos -= 30;
  
  // Client name
  streamContent += `BT /F1 14 Tf ${margin} ${yPos} Td (Client: ${escapeText(data.clientName)}) Tj ET\n`;
  yPos -= 20;
  
  // Date range
  const fromFormatted = formatDate(data.fromDate).split(',')[0];
  const toFormatted = formatDate(data.toDate).split(',')[0];
  streamContent += `BT /F2 11 Tf ${margin} ${yPos} Td (Period: ${fromFormatted} to ${toFormatted}) Tj ET\n`;
  yPos -= 16;
  
  // Generated info
  streamContent += `BT /F2 10 Tf ${margin} ${yPos} Td (Generated: ${formatDate(data.generatedAt)} by ${escapeText(data.generatedBy)}) Tj ET\n`;
  yPos -= 16;
  
  // Event count
  streamContent += `BT /F2 10 Tf ${margin} ${yPos} Td (Total Events: ${data.events.length}) Tj ET\n`;
  yPos -= 30;
  
  // Horizontal line
  streamContent += `${margin} ${yPos + 10} m ${pageWidth - margin} ${yPos + 10} l S\n`;
  yPos -= 10;
  
  // Events by section
  for (const [eventType, events] of Object.entries(eventsByType)) {
    if (yPos < 100) {
      // Would need new page - for simplicity, just continue
      yPos = 750;
    }
    
    // Section header
    streamContent += `BT /F1 12 Tf ${margin} ${yPos} Td (${formatEventType(eventType)} \\(${events.length}\\)) Tj ET\n`;
    yPos -= 20;
    
    // Events in this section (limit to 20 per section for PDF size)
    const displayEvents = events.slice(0, 20);
    for (const event of displayEvents) {
      if (yPos < 80) {
        yPos = 750;
      }
      
      const timestamp = formatDate(event.occurred_at);
      const title = escapeText(event.title || 'Untitled');
      const actor = escapeText(event.creator_name || 'System');
      
      // Bullet point with timestamp
      streamContent += `BT /F2 9 Tf ${margin + 10} ${yPos} Td (\\267 ${timestamp}) Tj ET\n`;
      yPos -= lineHeight;
      
      // Title
      streamContent += `BT /F2 10 Tf ${margin + 20} ${yPos} Td (${title}) Tj ET\n`;
      yPos -= lineHeight;
      
      // Actor
      streamContent += `BT /F2 9 Tf ${margin + 20} ${yPos} Td (By: ${actor}) Tj ET\n`;
      yPos -= lineHeight + 4;
    }
    
    if (events.length > 20) {
      streamContent += `BT /F2 9 Tf ${margin + 10} ${yPos} Td (... and ${events.length - 20} more events) Tj ET\n`;
      yPos -= lineHeight;
    }
    
    yPos -= 10;
  }
  
  // Footer
  if (yPos > 50) {
    yPos = 40;
    streamContent += `BT /F2 8 Tf ${margin} ${yPos} Td (Unicorn 2.0 - Vivacity Coaching & Consulting - Confidential) Tj ET\n`;
  }

  // Build PDF structure
  const objects: string[] = [];
  
  // Object 1: Catalog
  objects.push('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n');
  
  // Object 2: Pages
  objects.push('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n');
  
  // Object 3: Page
  objects.push(`3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>\nendobj\n`);
  
  // Object 4: Content stream
  const stream = streamContent;
  objects.push(`4 0 obj\n<< /Length ${stream.length} >>\nstream\n${stream}endstream\nendobj\n`);
  
  // Object 5: Font (Helvetica Bold)
  objects.push('5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n');
  
  // Object 6: Font (Helvetica)
  objects.push('6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n');
  
  // Build full PDF
  let pdf = '%PDF-1.4\n%âãÏÓ\n';
  const offsets: number[] = [];
  
  for (const obj of objects) {
    offsets.push(pdf.length);
    pdf += obj;
  }
  
  // xref table
  const xrefOffset = pdf.length;
  pdf += 'xref\n';
  pdf += `0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (const offset of offsets) {
    pdf += `${offset.toString().padStart(10, '0')} 00000 n \n`;
  }
  
  // trailer
  pdf += 'trailer\n';
  pdf += `<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += 'startxref\n';
  pdf += `${xrefOffset}\n`;
  pdf += '%%EOF\n';
  
  // Convert to base64
  const encoder = new TextEncoder();
  const bytes = encoder.encode(pdf);
  const base64 = btoa(String.fromCharCode(...bytes));
  
  return base64;
}