// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's identity: user id, email, and the tenants they can access via ComplyHub RLS.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: memberships, error } = await supabase.from("tenant_users").select("tenant_id, tenants(name)").limit(50);
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    const identity = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      tenants: memberships ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(identity, null, 2) }],
      structuredContent: identity
    };
  }
});

// src/lib/mcp/tools/list-my-tenants.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_my_tenants_default = defineTool2({
  name: "list_my_tenants",
  title: "List my tenants",
  description: "List the ComplyHub client tenants (RTOs) the signed-in user has access to, honouring tenant RLS.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("tenants").select("tenant_id, name, status, rto_code, abn").order("name").limit(200);
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tenants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-tasks.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.23.8";
var list_my_tasks_default = defineTool3({
  name: "list_my_tasks",
  title: "List my tasks",
  description: "List tasks assigned to the signed-in user. Respects tenant RLS: only tasks the user can see in ComplyHub are returned.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of tasks to return (default 25, max 100)."),
    status: z.string().optional().describe("Optional task status filter (e.g. 'open', 'in_progress', 'done').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let query = supabase.from("tasks").select("id, title, status, due_date, tenant_id, assigned_to, created_at").eq("assigned_to", ctx.getUserId()).order("due_date", { ascending: true, nullsFirst: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        { type: "text", text: JSON.stringify(data ?? [], null, 2) }
      ],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yxkgdalkbrriasiyyrwk";
var mcp_default = defineMcp({
  name: "complyhub-mcp",
  title: "ComplyHub",
  version: "0.1.0",
  instructions: "Tools for ComplyHub, a compliance platform for Australian RTOs. Use `whoami` to confirm the signed-in user, `list_my_tenants` to see which client organisations they can access, and `list_my_tasks` to see tasks assigned to them. All tools honour tenant-scoped RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_tenants_default, list_my_tasks_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
