-- Create documents_tenants table that mirrors documents schema plus tenant_id
CREATE TABLE public.documents_tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  format TEXT,
  watermark BOOLEAN DEFAULT false,
  versiondate DATE,
  versionnumber INTEGER,
  versionlastupdated TIMESTAMPTZ,
  isclientdoc BOOLEAN DEFAULT false,
  stage INTEGER,
  category INTEGER,
  uploaded_files TEXT[],
  file_names TEXT[],
  sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.documents_tenants ENABLE ROW LEVEL SECURITY;

-- Create policies for documents_tenants
-- Super Admins can see all
CREATE POLICY "Super Admins can view all documents_tenants"
ON public.documents_tenants
FOR SELECT
USING (is_super_admin());

-- Users can see documents sent to their tenant
CREATE POLICY "Users can view their tenant documents"
ON public.documents_tenants
FOR SELECT
USING (
  tenant_id = get_current_user_tenant()
);

-- Super Admins can manage all
CREATE POLICY "Super Admins can manage all documents_tenants"
ON public.documents_tenants
FOR ALL
USING (is_super_admin())
WITH CHECK (is_super_admin());

-- Create index for performance
CREATE INDEX idx_documents_tenants_tenant_id ON public.documents_tenants(tenant_id);
CREATE INDEX idx_documents_tenants_document_id ON public.documents_tenants(document_id);
CREATE INDEX idx_documents_tenants_sent_at ON public.documents_tenants(sent_at);

-- Add trigger for updated_at
CREATE TRIGGER update_documents_tenants_updated_at
BEFORE UPDATE ON public.documents_tenants
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();
