-- Create audit_inspection table for storing submitted inspections
CREATE TABLE public.audit_inspection (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id bigint NOT NULL REFERENCES public.audit_templates(id) ON DELETE CASCADE,
  tenant_id bigint NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  client_id uuid REFERENCES public.clients_legacy(id) ON DELETE SET NULL,
  inspection_title text NOT NULL,
  doc_number text,
  status text NOT NULL DEFAULT 'completed',
  compliance_score numeric(5,2),
  conducted_by uuid NOT NULL,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone DEFAULT now(),
  responses jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.audit_inspection ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "audit_inspection_select" ON public.audit_inspection
  FOR SELECT USING (is_super_admin() OR user_in_tenant(tenant_id));

CREATE POLICY "audit_inspection_insert" ON public.audit_inspection
  FOR INSERT WITH CHECK (user_in_tenant(tenant_id) AND (conducted_by = auth.uid()));

CREATE POLICY "audit_inspection_update" ON public.audit_inspection
  FOR UPDATE USING (user_in_tenant(tenant_id));

CREATE POLICY "audit_inspection_delete" ON public.audit_inspection
  FOR DELETE USING (is_super_admin() OR (user_in_tenant(tenant_id) AND (conducted_by = auth.uid())));

-- Create updated_at trigger
CREATE TRIGGER update_audit_inspection_updated_at
  BEFORE UPDATE ON public.audit_inspection
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();