-- Create custom email templates table
CREATE TABLE public.email_templates_custom (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  subject text,
  content text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid REFERENCES auth.users(id)
);

-- Enable RLS
ALTER TABLE public.email_templates_custom ENABLE ROW LEVEL SECURITY;

-- Create policy for Super Admins to manage templates
CREATE POLICY "Super admins can manage email templates"
ON public.email_templates_custom
FOR ALL
USING (public.is_super_admin())
WITH CHECK (public.is_super_admin());