-- Create audit_templates table for storing template metadata
CREATE TABLE public.audit_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES public.tenants(id),
  name text NOT NULL DEFAULT 'Untitled template',
  description text,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'locked')),
  access text NOT NULL DEFAULT 'all_users' CHECK (access IN ('all_users', 'restricted')),
  created_by uuid NOT NULL DEFAULT auth.uid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_published timestamp with time zone
);

-- Create audit_template_questions table for storing questions within templates
CREATE TABLE public.audit_template_questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id bigint NOT NULL REFERENCES public.audit_templates(id) ON DELETE CASCADE,
  question_type text NOT NULL,
  label text NOT NULL,
  order_index integer NOT NULL DEFAULT 0,
  options jsonb DEFAULT '[]'::jsonb,
  required boolean NOT NULL DEFAULT false,
  category text NOT NULL DEFAULT 'other_responses',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Create audit_template_response_sets table for custom response sets
CREATE TABLE public.audit_template_response_sets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id bigint REFERENCES public.audit_templates(id) ON DELETE CASCADE,
  tenant_id bigint REFERENCES public.tenants(id),
  name text NOT NULL,
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_global boolean NOT NULL DEFAULT false,
  created_by uuid NOT NULL DEFAULT auth.uid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.audit_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_template_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_template_response_sets ENABLE ROW LEVEL SECURITY;

-- RLS policies for audit_templates
CREATE POLICY "audit_templates_select" ON public.audit_templates
  FOR SELECT USING (is_super_admin() OR user_in_tenant(tenant_id));

CREATE POLICY "audit_templates_insert" ON public.audit_templates
  FOR INSERT WITH CHECK (user_in_tenant(tenant_id) AND created_by = auth.uid());

CREATE POLICY "audit_templates_update" ON public.audit_templates
  FOR UPDATE USING (user_in_tenant(tenant_id));

CREATE POLICY "audit_templates_delete" ON public.audit_templates
  FOR DELETE USING (is_super_admin() OR (user_in_tenant(tenant_id) AND created_by = auth.uid()));

-- RLS policies for audit_template_questions
CREATE POLICY "audit_template_questions_select" ON public.audit_template_questions
  FOR SELECT USING (
    is_super_admin() OR 
    EXISTS (SELECT 1 FROM public.audit_templates t WHERE t.id = template_id AND user_in_tenant(t.tenant_id))
  );

CREATE POLICY "audit_template_questions_insert" ON public.audit_template_questions
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.audit_templates t WHERE t.id = template_id AND user_in_tenant(t.tenant_id))
  );

CREATE POLICY "audit_template_questions_update" ON public.audit_template_questions
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.audit_templates t WHERE t.id = template_id AND user_in_tenant(t.tenant_id))
  );

CREATE POLICY "audit_template_questions_delete" ON public.audit_template_questions
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.audit_templates t WHERE t.id = template_id AND user_in_tenant(t.tenant_id))
  );

-- RLS policies for audit_template_response_sets
CREATE POLICY "audit_template_response_sets_select" ON public.audit_template_response_sets
  FOR SELECT USING (
    is_super_admin() OR 
    (is_global = true) OR 
    user_in_tenant(tenant_id) OR
    EXISTS (SELECT 1 FROM public.audit_templates t WHERE t.id = template_id AND user_in_tenant(t.tenant_id))
  );

CREATE POLICY "audit_template_response_sets_insert" ON public.audit_template_response_sets
  FOR INSERT WITH CHECK (
    user_in_tenant(tenant_id) OR
    EXISTS (SELECT 1 FROM public.audit_templates t WHERE t.id = template_id AND user_in_tenant(t.tenant_id))
  );

CREATE POLICY "audit_template_response_sets_update" ON public.audit_template_response_sets
  FOR UPDATE USING (
    user_in_tenant(tenant_id) OR
    EXISTS (SELECT 1 FROM public.audit_templates t WHERE t.id = template_id AND user_in_tenant(t.tenant_id))
  );

CREATE POLICY "audit_template_response_sets_delete" ON public.audit_template_response_sets
  FOR DELETE USING (
    is_super_admin() OR
    (user_in_tenant(tenant_id) AND created_by = auth.uid())
  );

-- Create indexes for better performance
CREATE INDEX idx_audit_templates_tenant_id ON public.audit_templates(tenant_id);
CREATE INDEX idx_audit_template_questions_template_id ON public.audit_template_questions(template_id);
CREATE INDEX idx_audit_template_response_sets_template_id ON public.audit_template_response_sets(template_id);
CREATE INDEX idx_audit_template_response_sets_tenant_id ON public.audit_template_response_sets(tenant_id);