
-- Replace v_clickup_tasks to read from the new clickup_tasks_api table
-- with column aliases matching the legacy view for UI compatibility
DROP VIEW IF EXISTS public.v_clickup_tasks;

CREATE VIEW public.v_clickup_tasks
WITH (security_invoker = true)
AS
SELECT
  id,
  task_id,
  custom_id AS task_custom_id,
  name AS task_name,
  description AS task_content,
  status,
  priority,
  date_created,
  date_updated,
  date_closed,
  date_done,
  due_date,
  start_date,
  time_estimate,
  time_spent,
  assignees,
  watchers,
  tags,
  checklists,
  list_id,
  list_name,
  folder_id,
  folder_name,
  space_id,
  space_name,
  url,
  creator_id,
  creator_username,
  custom_fields,
  unicorn_url,
  sharepoint_url,
  mb_level,
  risk,
  rto_id,
  phone,
  email_address,
  audit_date,
  mock_audit,
  cricos_rereg_date,
  registration_date,
  re_reg_due_date,
  submission_date,
  working_hours,
  notes,
  infusionsoft_url,
  date_of_last_contact,
  date_of_last_systemscheck,
  client_meeting_attendance,
  time_with_vivacity,
  registered_spr,
  on_hold_start_date,
  on_hold_end_date,
  tenant_id,
  raw_json,
  fetched_at
FROM public.clickup_tasks_api;
