-- ============================================================
-- Phase 1: Schema Changes + Backfill for Client-First Refactor
-- ============================================================

-- 1. Create stage_state enum if not exists
DO $$ BEGIN
  CREATE TYPE stage_state AS ENUM ('not_started', 'active', 'blocked', 'complete', 'not_applicable');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- 2. Add missing 'backlog' value to task_status enum if not present
DO $$ BEGIN
  ALTER TYPE task_status ADD VALUE IF NOT EXISTS 'backlog' BEFORE 'not_started';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- 3. Create package_stages table (package-stage catalog mapping)
CREATE TABLE IF NOT EXISTS public.package_stages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id bigint NOT NULL REFERENCES public.packages(id) ON DELETE CASCADE,
  stage_id bigint NOT NULL REFERENCES public.documents_stages(id) ON DELETE CASCADE,
  sort_order int NOT NULL DEFAULT 0,
  dashboard_group text NULL,
  is_required boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid NULL,
  UNIQUE(package_id, stage_id)
);

-- Add comment for clarity
COMMENT ON TABLE public.package_stages IS 'Maps which stages belong to which packages (catalog-level). Replaces tenants.stage_ids[] array usage.';
COMMENT ON COLUMN public.package_stages.dashboard_group IS 'Grouping for dashboard display: ONBOARDING, ONGOING_ACCESS, USAGE_SUPPORT, ANNUAL_OBLIGATIONS';

-- 4. Create tenant_users table (parent/child accounts per tenant)
CREATE TABLE IF NOT EXISTS public.tenant_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'child' CHECK (role IN ('parent', 'child')),
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid NULL,
  UNIQUE(tenant_id, user_id)
);

COMMENT ON TABLE public.tenant_users IS 'Tenant-scoped user memberships. Parent users can manage, child users have read-only access to tenant content.';

-- 5. Create enhanced client_audit_log table if client_audit_log doesn't have all needed columns
-- (We already have client_audit_log, so we'll add missing columns if needed)
DO $$ 
BEGIN
  -- Add before/after columns if they don't exist
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'client_audit_log' AND column_name = 'before_data') THEN
    ALTER TABLE public.client_audit_log ADD COLUMN before_data jsonb NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'client_audit_log' AND column_name = 'after_data') THEN
    ALTER TABLE public.client_audit_log ADD COLUMN after_data jsonb NULL;
  END IF;
END $$;

-- 6. Add TGA linkage fields to tenants if not present
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tenants' AND column_name = 'rto_id') THEN
    ALTER TABLE public.tenants ADD COLUMN rto_id text NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tenants' AND column_name = 'cricos_id') THEN
    ALTER TABLE public.tenants ADD COLUMN cricos_id text NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tenants' AND column_name = 'tga_sync_status') THEN
    ALTER TABLE public.tenants ADD COLUMN tga_sync_status text NULL;
  END IF;
END $$;

-- 7. Add due_at and notes to client_package_stage_state if not present
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'client_package_stage_state' AND column_name = 'due_at') THEN
    ALTER TABLE public.client_package_stage_state ADD COLUMN due_at timestamptz NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'client_package_stage_state' AND column_name = 'notes') THEN
    ALTER TABLE public.client_package_stage_state ADD COLUMN notes text NULL;
  END IF;
END $$;

-- ============================================================
-- BACKFILL SCRIPTS
-- ============================================================

-- 8. Backfill package_stages from tenants.stage_ids[] arrays
-- For each package in use, collect all stage_ids from tenants on that package
INSERT INTO public.package_stages (package_id, stage_id, sort_order, is_required, created_at)
SELECT DISTINCT 
  me.package_id,
  unnest_stage_id,
  0 as sort_order,
  true as is_required,
  now() as created_at
FROM public.membership_entitlements me
CROSS JOIN LATERAL (
  SELECT unnest(t.stage_ids::bigint[]) as unnest_stage_id
  FROM public.tenants t
  WHERE t.id = me.tenant_id
  AND t.stage_ids IS NOT NULL
  AND array_length(t.stage_ids::bigint[], 1) > 0
) stages
WHERE EXISTS (SELECT 1 FROM public.documents_stages ds WHERE ds.id = stages.unnest_stage_id)
ON CONFLICT (package_id, stage_id) DO NOTHING;

-- Also backfill from tenants.package_ids array
INSERT INTO public.package_stages (package_id, stage_id, sort_order, is_required, created_at)
SELECT DISTINCT 
  pkg_id,
  unnest_stage_id,
  0 as sort_order,
  true as is_required,
  now() as created_at
FROM public.tenants t
CROSS JOIN LATERAL unnest(t.package_ids::bigint[]) as pkg_id
CROSS JOIN LATERAL (
  SELECT unnest(t.stage_ids::bigint[]) as unnest_stage_id
) stages
WHERE t.stage_ids IS NOT NULL
AND t.package_ids IS NOT NULL
AND array_length(t.stage_ids::bigint[], 1) > 0
AND EXISTS (SELECT 1 FROM public.packages p WHERE p.id = pkg_id)
AND EXISTS (SELECT 1 FROM public.documents_stages ds WHERE ds.id = stages.unnest_stage_id)
ON CONFLICT (package_id, stage_id) DO NOTHING;

-- 9. Backfill client_package_stage_state for existing entitlements
-- Create rows for each tenant/package/stage combination based on package_stages
INSERT INTO public.client_package_stage_state (tenant_id, package_id, stage_id, status, is_required, sort_order, created_at)
SELECT 
  me.tenant_id,
  me.package_id,
  ps.stage_id,
  'not_started' as status,
  ps.is_required,
  ps.sort_order,
  now()
FROM public.membership_entitlements me
JOIN public.package_stages ps ON ps.package_id = me.package_id
WHERE NOT EXISTS (
  SELECT 1 FROM public.client_package_stage_state cpss 
  WHERE cpss.tenant_id = me.tenant_id 
  AND cpss.package_id = me.package_id 
  AND cpss.stage_id = ps.stage_id
)
ON CONFLICT (tenant_id, package_id, stage_id) DO NOTHING;

-- 10. Sync rto_number from tenant_profile to tenants.rto_id
UPDATE public.tenants t
SET rto_id = tp.rto_number
FROM public.tenant_profile tp
WHERE tp.tenant_id = t.id
AND tp.rto_number IS NOT NULL
AND t.rto_id IS NULL;

-- Sync cricos_number from tenant_profile to tenants.cricos_id
UPDATE public.tenants t
SET cricos_id = tp.cricos_number
FROM public.tenant_profile tp
WHERE tp.tenant_id = t.id
AND tp.cricos_number IS NOT NULL
AND t.cricos_id IS NULL;

-- ============================================================
-- RLS POLICIES
-- ============================================================

-- Enable RLS on new tables
ALTER TABLE public.package_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_users ENABLE ROW LEVEL SECURITY;

-- package_stages: readable by authenticated users, writable by admins
CREATE POLICY "package_stages_select_authenticated" ON public.package_stages
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "package_stages_insert_authenticated" ON public.package_stages
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "package_stages_update_authenticated" ON public.package_stages
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "package_stages_delete_authenticated" ON public.package_stages
  FOR DELETE TO authenticated USING (true);

-- tenant_users: users can see their own tenant memberships
CREATE POLICY "tenant_users_select_own" ON public.tenant_users
  FOR SELECT TO authenticated 
  USING (user_id = auth.uid() OR EXISTS (
    SELECT 1 FROM public.tenant_users tu2 
    WHERE tu2.tenant_id = tenant_users.tenant_id 
    AND tu2.user_id = auth.uid() 
    AND tu2.role = 'parent'
  ));

CREATE POLICY "tenant_users_insert_parent" ON public.tenant_users
  FOR INSERT TO authenticated 
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.tenant_users tu2 
    WHERE tu2.tenant_id = tenant_users.tenant_id 
    AND tu2.user_id = auth.uid() 
    AND tu2.role = 'parent'
  ) OR NOT EXISTS (
    SELECT 1 FROM public.tenant_users tu3 WHERE tu3.tenant_id = tenant_users.tenant_id
  ));

CREATE POLICY "tenant_users_delete_parent" ON public.tenant_users
  FOR DELETE TO authenticated 
  USING (EXISTS (
    SELECT 1 FROM public.tenant_users tu2 
    WHERE tu2.tenant_id = tenant_users.tenant_id 
    AND tu2.user_id = auth.uid() 
    AND tu2.role = 'parent'
  ));

-- ============================================================
-- INDEXES for performance
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_package_stages_package_id ON public.package_stages(package_id);
CREATE INDEX IF NOT EXISTS idx_package_stages_stage_id ON public.package_stages(stage_id);
CREATE INDEX IF NOT EXISTS idx_tenant_users_tenant_id ON public.tenant_users(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_users_user_id ON public.tenant_users(user_id);
CREATE INDEX IF NOT EXISTS idx_client_package_stage_state_tenant_package ON public.client_package_stage_state(tenant_id, package_id);
CREATE INDEX IF NOT EXISTS idx_tenants_rto_id ON public.tenants(rto_id) WHERE rto_id IS NOT NULL;