CREATE TABLE public.dd_obligation_audience (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text       NOT NULL UNIQUE,
  label       text       NOT NULL,
  sort_order  integer    NOT NULL DEFAULT 0,
  is_active   boolean    NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.dd_obligation_audience TO authenticated;
GRANT ALL    ON public.dd_obligation_audience TO service_role;

ALTER TABLE public.dd_obligation_audience ENABLE ROW LEVEL SECURITY;

CREATE POLICY dd_obligation_audience_read
  ON public.dd_obligation_audience
  FOR SELECT
  USING (true);

CREATE POLICY dd_obligation_audience_admin
  ON public.dd_obligation_audience
  FOR ALL
  USING (public.is_vivacity())
  WITH CHECK (public.is_vivacity());

CREATE TABLE public.dd_obligation_recurrence (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text       NOT NULL UNIQUE,
  label       text       NOT NULL,
  sort_order  integer    NOT NULL DEFAULT 0,
  is_active   boolean    NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.dd_obligation_recurrence TO authenticated;
GRANT ALL    ON public.dd_obligation_recurrence TO service_role;

ALTER TABLE public.dd_obligation_recurrence ENABLE ROW LEVEL SECURITY;

CREATE POLICY dd_obligation_recurrence_read
  ON public.dd_obligation_recurrence
  FOR SELECT
  USING (true);

CREATE POLICY dd_obligation_recurrence_admin
  ON public.dd_obligation_recurrence
  FOR ALL
  USING (public.is_vivacity())
  WITH CHECK (public.is_vivacity());

INSERT INTO public.dd_obligation_audience (value, label, sort_order) VALUES
  ('rto',           'RTO',           10),
  ('cricos',        'CRICOS',        20),
  ('rto_or_cricos', 'RTO or CRICOS', 30)
ON CONFLICT (value) DO NOTHING;

INSERT INTO public.dd_obligation_recurrence (value, label, sort_order) VALUES
  ('annual_fixed',       'Annual — fixed date', 10),
  ('annual_window',      'Annual — window',     20),
  ('rolling_per_tenant', 'Rolling per tenant',  30),
  ('always_open',        'Always open',         40)
ON CONFLICT (value) DO NOTHING;