
-- ============================================================
-- GOVERNANCE DOCUMENTS — PHASE 1 SCHEMA MIGRATION
-- ============================================================

-- 1a. TRUNCATE stage_documents and ADD columns
TRUNCATE TABLE stage_documents;

ALTER TABLE stage_documents
  ADD COLUMN IF NOT EXISTS is_core boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_by uuid,
  ADD COLUMN IF NOT EXISTS added_source text DEFAULT 'manual';

-- Add updated_at trigger
DROP TRIGGER IF EXISTS set_stage_documents_updated_at ON stage_documents;
CREATE TRIGGER set_stage_documents_updated_at
  BEFORE UPDATE ON stage_documents
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 1b. ALTER document_instances — add generation tracking columns
ALTER TABLE document_instances
  ADD COLUMN IF NOT EXISTS generated_file_url text,
  ADD COLUMN IF NOT EXISTS generated_item_id text,
  ADD COLUMN IF NOT EXISTS generation_status text DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS last_error text,
  ADD COLUMN IF NOT EXISTS updated_by uuid,
  ADD COLUMN IF NOT EXISTS is_manual_allocation boolean NOT NULL DEFAULT false;

-- 1c. CREATE document_generation_errors
CREATE TABLE IF NOT EXISTS document_generation_errors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documentinstance_id bigint NOT NULL REFERENCES document_instances(id) ON DELETE CASCADE,
  error_code text,
  error_message text NOT NULL,
  error_detail jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  resolved_by uuid
);

CREATE INDEX IF NOT EXISTS idx_dge_instance ON document_generation_errors(documentinstance_id);
CREATE INDEX IF NOT EXISTS idx_dge_unresolved ON document_generation_errors(documentinstance_id) WHERE resolved_at IS NULL;

-- 1d. CREATE lookup tables
CREATE TABLE IF NOT EXISTS dd_document_status (
  id serial PRIMARY KEY,
  value text UNIQUE NOT NULL,
  label text NOT NULL,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS dd_doc_generation_status (
  id serial PRIMARY KEY,
  value text UNIQUE NOT NULL,
  label text NOT NULL,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS dd_governance_framework (
  id serial PRIMARY KEY,
  value text UNIQUE NOT NULL,
  label text NOT NULL,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true
);

-- Seed lookup tables
INSERT INTO dd_document_status (value, label, sort_order) VALUES
  ('draft', 'Draft', 1),
  ('released', 'Released', 2),
  ('superseded', 'Superseded', 3),
  ('archived', 'Archived', 4)
ON CONFLICT (value) DO NOTHING;

INSERT INTO dd_doc_generation_status (value, label, sort_order) VALUES
  ('pending', 'Pending', 1),
  ('generating', 'Generating', 2),
  ('generated', 'Generated', 3),
  ('failed', 'Failed', 4),
  ('skipped', 'Skipped', 5)
ON CONFLICT (value) DO NOTHING;

INSERT INTO dd_governance_framework (value, label, sort_order) VALUES
  ('RTO2015', 'Standards for RTOs 2015', 1),
  ('RTO2025', 'Standards for RTOs 2025', 2),
  ('CRICOS', 'CRICOS National Code', 3),
  ('GTO', 'GTO Compliance', 4)
ON CONFLICT (value) DO NOTHING;

-- 1e. Feature flags in app_settings
ALTER TABLE app_settings
  ADD COLUMN IF NOT EXISTS governance_use_stage_documents boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS governance_overwrite_enabled boolean DEFAULT false;

-- 1f. RLS policies

-- document_generation_errors
ALTER TABLE document_generation_errors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenant members can view generation errors"
  ON document_generation_errors FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM document_instances di
      WHERE di.id = document_generation_errors.documentinstance_id
        AND di.tenant_id IN (
          SELECT tu.tenant_id FROM tenant_users tu WHERE tu.user_id = auth.uid()
        )
    )
    OR is_super_admin_safe(auth.uid())
  );

CREATE POLICY "SuperAdmin can manage generation errors"
  ON document_generation_errors FOR ALL TO authenticated
  USING (is_super_admin_safe(auth.uid()))
  WITH CHECK (is_super_admin_safe(auth.uid()));

-- stage_documents — add VivacityTeam write alongside existing SuperAdmin policies
CREATE POLICY "VivacityTeam can manage stage_documents"
  ON stage_documents FOR ALL TO authenticated
  USING (is_vivacity_team_safe(auth.uid()))
  WITH CHECK (is_vivacity_team_safe(auth.uid()));

-- dd_ tables RLS
ALTER TABLE dd_document_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE dd_doc_generation_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE dd_governance_framework ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can view dd_document_status"
  ON dd_document_status FOR SELECT TO authenticated USING (true);
CREATE POLICY "SuperAdmin can manage dd_document_status"
  ON dd_document_status FOR ALL TO authenticated
  USING (is_super_admin_safe(auth.uid()))
  WITH CHECK (is_super_admin_safe(auth.uid()));

CREATE POLICY "Authenticated can view dd_doc_generation_status"
  ON dd_doc_generation_status FOR SELECT TO authenticated USING (true);
CREATE POLICY "SuperAdmin can manage dd_doc_generation_status"
  ON dd_doc_generation_status FOR ALL TO authenticated
  USING (is_super_admin_safe(auth.uid()))
  WITH CHECK (is_super_admin_safe(auth.uid()));

CREATE POLICY "Authenticated can view dd_governance_framework"
  ON dd_governance_framework FOR SELECT TO authenticated USING (true);
CREATE POLICY "SuperAdmin can manage dd_governance_framework"
  ON dd_governance_framework FOR ALL TO authenticated
  USING (is_super_admin_safe(auth.uid()))
  WITH CHECK (is_super_admin_safe(auth.uid()));

-- 1g. FIX Bug 1: v_completion_eligibility — sd.id → sd.document_id
CREATE OR REPLACE VIEW v_completion_eligibility WITH (security_invoker = true) AS
WITH stage_counts AS (
  SELECT cpss.tenant_id,
    cpss.package_id,
    count(*) FILTER (WHERE cpss.is_required = true) AS total_required,
    count(*) FILTER (WHERE cpss.is_required = true AND cpss.status = 'complete') AS completed_required
  FROM client_package_stage_state cpss
  GROUP BY cpss.tenant_id, cpss.package_id
), doc_counts AS (
  SELECT cpss.tenant_id,
    cpss.package_id,
    count(*) FILTER (WHERE sd.is_required = true) AS total_required_docs,
    count(*) FILTER (WHERE sd.is_required = true AND EXISTS (
      SELECT 1 FROM document_instances di
      WHERE di.document_id = sd.document_id AND di.tenant_id = cpss.tenant_id
    )) AS present_required_docs
  FROM client_package_stage_state cpss
    JOIN stage_documents sd ON sd.stage_id = cpss.stage_id
  GROUP BY cpss.tenant_id, cpss.package_id
)
SELECT pi.tenant_id,
  pi.id AS package_instance_id,
  pi.package_id,
  COALESCE(sc.total_required, 0::bigint) > 0 AND COALESCE(sc.completed_required, 0::bigint) = COALESCE(sc.total_required, 0::bigint) AS is_final_phase_completed,
  CASE
    WHEN COALESCE(dc.total_required_docs, 0::bigint) = 0 THEN 0.0
    ELSE round(1.0 - COALESCE(dc.present_required_docs, 0::bigint)::numeric / dc.total_required_docs::numeric, 2)
  END AS missing_required_docs_ratio,
  EXISTS (
    SELECT 1 FROM eos_issues ei
    WHERE ei.tenant_id = pi.tenant_id AND ei.deleted_at IS NULL
      AND ei.status NOT IN ('Solved', 'Closed', 'Archived')
      AND ei.resolved_at IS NULL
      AND (ei.impact = 'Critical' OR ei.impact = 'critical')
  ) AS has_active_critical,
  COALESCE(sc.total_required, 0::bigint) > 0
    AND COALESCE(sc.completed_required, 0::bigint) = COALESCE(sc.total_required, 0::bigint)
    AND NOT EXISTS (
      SELECT 1 FROM eos_issues ei
      WHERE ei.tenant_id = pi.tenant_id AND ei.deleted_at IS NULL
        AND ei.status NOT IN ('Solved', 'Closed', 'Archived')
        AND ei.resolved_at IS NULL
        AND (ei.impact = 'Critical' OR ei.impact = 'critical')
    )
    AND (COALESCE(dc.total_required_docs, 0::bigint) = 0
      OR (COALESCE(dc.present_required_docs, 0::bigint)::numeric / NULLIF(dc.total_required_docs, 0)::numeric) >= 0.80)
  AS eligible,
  array_remove(ARRAY[
    CASE WHEN NOT (COALESCE(sc.total_required, 0::bigint) > 0 AND COALESCE(sc.completed_required, 0::bigint) = COALESCE(sc.total_required, 0::bigint)) THEN 'phases_incomplete' ELSE NULL END,
    CASE WHEN EXISTS (
      SELECT 1 FROM eos_issues ei
      WHERE ei.tenant_id = pi.tenant_id AND ei.deleted_at IS NULL
        AND ei.status NOT IN ('Solved', 'Closed', 'Archived')
        AND ei.resolved_at IS NULL
        AND (ei.impact = 'Critical' OR ei.impact = 'critical')
    ) THEN 'active_critical_risk' ELSE NULL END,
    CASE WHEN COALESCE(dc.total_required_docs, 0::bigint) > 0 AND (COALESCE(dc.present_required_docs, 0::bigint)::numeric / NULLIF(dc.total_required_docs, 0)::numeric) < 0.80 THEN 'missing_required_docs' ELSE NULL END
  ], NULL) AS ineligible_reasons
FROM package_instances pi
  LEFT JOIN stage_counts sc ON sc.tenant_id = pi.tenant_id AND sc.package_id = pi.package_id
  LEFT JOIN doc_counts dc ON dc.tenant_id = pi.tenant_id AND dc.package_id = pi.package_id
WHERE pi.is_complete = false;

-- 1g. FIX Bug 2: v_progress_anchor_inputs — sd.id → sd.document_id
CREATE OR REPLACE VIEW v_progress_anchor_inputs WITH (security_invoker = true) AS
SELECT pi.tenant_id,
  pi.id AS package_instance_id,
  pi.package_id,
  t.name AS client_name,
  p.name AS package_name,
  COALESCE(cs.overall_score, 0) AS overall_score,
  COALESCE(cs.days_stale, 0) AS days_stale,
  COALESCE(cs.is_stale, false) AS is_stale,
  COALESCE((
    SELECT count(*) FROM client_package_stage_state cpss
    WHERE cpss.tenant_id = pi.tenant_id AND cpss.package_id = pi.package_id
      AND cpss.is_required = true AND cpss.status <> 'complete'
  ), 0)::integer AS actions_remaining_current_phase,
  COALESCE((
    SELECT count(*) FROM stage_documents sd
      JOIN client_package_stage_state cpss ON cpss.stage_id = sd.stage_id
        AND cpss.tenant_id = pi.tenant_id AND cpss.package_id = pi.package_id
    WHERE sd.is_required = true AND NOT EXISTS (
      SELECT 1 FROM document_instances di
      WHERE di.document_id = sd.document_id AND di.tenant_id = pi.tenant_id
    )
  ), 0)::integer AS documents_pending_upload,
  (
    SELECT ds.title FROM client_package_stage_state cpss
      JOIN documents_stages ds ON ds.id = cpss.stage_id
    WHERE cpss.tenant_id = pi.tenant_id AND cpss.package_id = pi.package_id
      AND cpss.is_required = true AND cpss.status <> 'complete'
    ORDER BY cpss.sort_order LIMIT 1
  ) AS next_milestone_label,
  EXISTS (
    SELECT 1 FROM eos_issues ei
    WHERE ei.tenant_id = pi.tenant_id AND ei.deleted_at IS NULL
      AND ei.status NOT IN ('Solved', 'Closed', 'Archived')
      AND ei.resolved_at IS NULL
      AND (ei.impact = 'Critical' OR ei.impact = 'critical')
  ) AS has_active_critical
FROM package_instances pi
  JOIN tenants t ON t.id = pi.tenant_id
  JOIN packages p ON p.id = pi.package_id
  LEFT JOIN v_compliance_score_latest cs ON cs.tenant_id = pi.tenant_id AND cs.package_instance_id = pi.id
WHERE pi.is_complete = false;

-- 1h. FIX Bug 3: publish_stage_version — fix column references
CREATE OR REPLACE FUNCTION public.publish_stage_version(p_stage_id bigint, p_notes text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  v_stage record;
  v_snapshot jsonb;
  v_team_tasks jsonb;
  v_client_tasks jsonb;
  v_emails jsonb;
  v_documents jsonb;
  v_next_version int;
  v_version_id uuid;
BEGIN
  SELECT * INTO v_stage
  FROM public.documents_stages
  WHERE id = p_stage_id;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Stage not found';
  END IF;
  
  SELECT COALESCE(MAX(version_number), 0) + 1
  INTO v_next_version
  FROM public.stage_versions
  WHERE stage_id = p_stage_id;
  
  -- FIX: use correct column names (title, stage_type; remove package_type)
  v_snapshot := jsonb_build_object(
    'stage', jsonb_build_object(
      'id', v_stage.id,
      'name', v_stage.title,
      'type', v_stage.stage_type,
      'description', v_stage.description,
      'ai_hint', v_stage.ai_hint,
      'is_certified', v_stage.is_certified,
      'certified_notes', v_stage.certified_notes
    )
  );
  
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'id', id, 'name', name, 'description', description,
      'owner_role', owner_role, 'estimated_hours', estimated_hours,
      'is_mandatory', is_mandatory, 'sort_order', sort_order
    ) ORDER BY sort_order
  ), '[]'::jsonb)
  INTO v_team_tasks
  FROM public.stage_team_tasks WHERE stage_id = p_stage_id;
  
  v_snapshot := v_snapshot || jsonb_build_object('team_tasks', v_team_tasks);
  
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'id', id, 'name', name, 'instructions', instructions,
      'required_documents', required_documents, 'sort_order', sort_order
    ) ORDER BY sort_order
  ), '[]'::jsonb)
  INTO v_client_tasks
  FROM public.stage_client_tasks WHERE stage_id = p_stage_id;
  
  v_snapshot := v_snapshot || jsonb_build_object('client_tasks', v_client_tasks);
  
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'id', se.id, 'email_template_id', se.email_template_id,
      'trigger_type', se.trigger_type, 'recipient_type', se.recipient_type,
      'is_active', se.is_active, 'sort_order', se.sort_order,
      'template_name', et.name
    ) ORDER BY se.sort_order
  ), '[]'::jsonb)
  INTO v_emails
  FROM public.stage_emails se
  LEFT JOIN public.email_templates et ON et.id = se.email_template_id
  WHERE se.stage_id = p_stage_id;
  
  v_snapshot := v_snapshot || jsonb_build_object('emails', v_emails);
  
  -- FIX: d.name → d.title, add is_core, is_active, is_required
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'id', sd.id, 'document_id', sd.document_id,
      'visibility', sd.visibility, 'delivery_type', sd.delivery_type,
      'sort_order', sd.sort_order, 'document_name', d.title,
      'is_core', sd.is_core, 'is_active', sd.is_active,
      'is_required', sd.is_required
    ) ORDER BY sd.sort_order
  ), '[]'::jsonb)
  INTO v_documents
  FROM public.stage_documents sd
  LEFT JOIN public.documents d ON d.id = sd.document_id
  WHERE sd.stage_id = p_stage_id;
  
  v_snapshot := v_snapshot || jsonb_build_object('documents', v_documents);
  
  INSERT INTO public.stage_versions (stage_id, version_number, status, notes, snapshot, created_by)
  VALUES (p_stage_id, v_next_version, 'published', p_notes, v_snapshot, auth.uid())
  RETURNING id INTO v_version_id;
  
  INSERT INTO public.audit_events (action, entity, entity_id, user_id, details)
  VALUES (
    'publish', 'stage_version', v_version_id::text, auth.uid(),
    jsonb_build_object('stage_id', p_stage_id, 'version', v_next_version, 'notes', p_notes)
  );
  
  RETURN v_version_id;
END;
$function$;

-- 1h-2. FIX Bug 4: get_document_stage_usage — ds.name → ds.title
CREATE OR REPLACE FUNCTION public.get_document_stage_usage(p_document_id bigint)
 RETURNS TABLE(stage_id bigint, stage_name text, package_count bigint, pinned_version_id uuid, pinned_version_number integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
BEGIN
  RETURN QUERY
  SELECT 
    sd.stage_id,
    ds.title,
    (SELECT COUNT(DISTINCT ps.package_id) FROM public.package_stages ps WHERE ps.stage_id = sd.stage_id),
    sd.pinned_version_id,
    dv.version_number
  FROM public.stage_documents sd
  JOIN public.documents_stages ds ON ds.id = sd.stage_id
  LEFT JOIN public.document_versions dv ON dv.id = sd.pinned_version_id
  WHERE sd.document_id = p_document_id;
END;
$function$;
