-- ============================================================
-- KPI Module — Phase 1: Foundation
-- 10 dd_kpi_* lookups, kpi_role on users, churned_at on tenants,
-- is_kpi_reviewer_safe() helper, audit trigger extension.
-- ============================================================

-- ---------- Lookup table helper (inline DDL repeated, no DO blocks) ----------

-- 1. dd_kpi_role
CREATE TABLE IF NOT EXISTS public.dd_kpi_role (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text        NOT NULL,
  label       text        NOT NULL,
  description text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dd_kpi_role_value_key UNIQUE (value)
);
GRANT SELECT ON public.dd_kpi_role TO authenticated;
GRANT ALL    ON public.dd_kpi_role TO service_role;
ALTER TABLE public.dd_kpi_role ENABLE ROW LEVEL SECURITY;
CREATE POLICY dd_kpi_role_select ON public.dd_kpi_role
  FOR SELECT TO authenticated USING (true);
CREATE POLICY dd_kpi_role_manage ON public.dd_kpi_role
  FOR ALL TO authenticated
  USING (public.is_super_admin_safe(auth.uid()))
  WITH CHECK (public.is_super_admin_safe(auth.uid()));
CREATE TRIGGER dd_kpi_role_updated_at BEFORE UPDATE ON public.dd_kpi_role
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 2. dd_kpi_period_type
CREATE TABLE IF NOT EXISTS public.dd_kpi_period_type (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text        NOT NULL,
  label       text        NOT NULL,
  description text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dd_kpi_period_type_value_key UNIQUE (value)
);
GRANT SELECT ON public.dd_kpi_period_type TO authenticated;
GRANT ALL    ON public.dd_kpi_period_type TO service_role;
ALTER TABLE public.dd_kpi_period_type ENABLE ROW LEVEL SECURITY;
CREATE POLICY dd_kpi_period_type_select ON public.dd_kpi_period_type
  FOR SELECT TO authenticated USING (true);
CREATE POLICY dd_kpi_period_type_manage ON public.dd_kpi_period_type
  FOR ALL TO authenticated
  USING (public.is_super_admin_safe(auth.uid()))
  WITH CHECK (public.is_super_admin_safe(auth.uid()));
CREATE TRIGGER dd_kpi_period_type_updated_at BEFORE UPDATE ON public.dd_kpi_period_type
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 3. dd_kpi_task_status
CREATE TABLE IF NOT EXISTS public.dd_kpi_task_status (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text        NOT NULL,
  label       text        NOT NULL,
  description text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dd_kpi_task_status_value_key UNIQUE (value)
);
GRANT SELECT ON public.dd_kpi_task_status TO authenticated;
GRANT ALL    ON public.dd_kpi_task_status TO service_role;
ALTER TABLE public.dd_kpi_task_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY dd_kpi_task_status_select ON public.dd_kpi_task_status
  FOR SELECT TO authenticated USING (true);
CREATE POLICY dd_kpi_task_status_manage ON public.dd_kpi_task_status
  FOR ALL TO authenticated
  USING (public.is_super_admin_safe(auth.uid()))
  WITH CHECK (public.is_super_admin_safe(auth.uid()));
CREATE TRIGGER dd_kpi_task_status_updated_at BEFORE UPDATE ON public.dd_kpi_task_status
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 4. dd_kpi_ticket_status
CREATE TABLE IF NOT EXISTS public.dd_kpi_ticket_status (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text        NOT NULL,
  label       text        NOT NULL,
  description text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dd_kpi_ticket_status_value_key UNIQUE (value)
);
GRANT SELECT ON public.dd_kpi_ticket_status TO authenticated;
GRANT ALL    ON public.dd_kpi_ticket_status TO service_role;
ALTER TABLE public.dd_kpi_ticket_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY dd_kpi_ticket_status_select ON public.dd_kpi_ticket_status
  FOR SELECT TO authenticated USING (true);
CREATE POLICY dd_kpi_ticket_status_manage ON public.dd_kpi_ticket_status
  FOR ALL TO authenticated
  USING (public.is_super_admin_safe(auth.uid()))
  WITH CHECK (public.is_super_admin_safe(auth.uid()));
CREATE TRIGGER dd_kpi_ticket_status_updated_at BEFORE UPDATE ON public.dd_kpi_ticket_status
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 5. dd_kpi_ticket_priority
CREATE TABLE IF NOT EXISTS public.dd_kpi_ticket_priority (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text        NOT NULL,
  label       text        NOT NULL,
  description text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dd_kpi_ticket_priority_value_key UNIQUE (value)
);
GRANT SELECT ON public.dd_kpi_ticket_priority TO authenticated;
GRANT ALL    ON public.dd_kpi_ticket_priority TO service_role;
ALTER TABLE public.dd_kpi_ticket_priority ENABLE ROW LEVEL SECURITY;
CREATE POLICY dd_kpi_ticket_priority_select ON public.dd_kpi_ticket_priority
  FOR SELECT TO authenticated USING (true);
CREATE POLICY dd_kpi_ticket_priority_manage ON public.dd_kpi_ticket_priority
  FOR ALL TO authenticated
  USING (public.is_super_admin_safe(auth.uid()))
  WITH CHECK (public.is_super_admin_safe(auth.uid()));
CREATE TRIGGER dd_kpi_ticket_priority_updated_at BEFORE UPDATE ON public.dd_kpi_ticket_priority
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 6. dd_kpi_ticket_platform
CREATE TABLE IF NOT EXISTS public.dd_kpi_ticket_platform (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text        NOT NULL,
  label       text        NOT NULL,
  description text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dd_kpi_ticket_platform_value_key UNIQUE (value)
);
GRANT SELECT ON public.dd_kpi_ticket_platform TO authenticated;
GRANT ALL    ON public.dd_kpi_ticket_platform TO service_role;
ALTER TABLE public.dd_kpi_ticket_platform ENABLE ROW LEVEL SECURITY;
CREATE POLICY dd_kpi_ticket_platform_select ON public.dd_kpi_ticket_platform
  FOR SELECT TO authenticated USING (true);
CREATE POLICY dd_kpi_ticket_platform_manage ON public.dd_kpi_ticket_platform
  FOR ALL TO authenticated
  USING (public.is_super_admin_safe(auth.uid()))
  WITH CHECK (public.is_super_admin_safe(auth.uid()));
CREATE TRIGGER dd_kpi_ticket_platform_updated_at BEFORE UPDATE ON public.dd_kpi_ticket_platform
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 7. dd_kpi_ticket_comm_type
CREATE TABLE IF NOT EXISTS public.dd_kpi_ticket_comm_type (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text        NOT NULL,
  label       text        NOT NULL,
  description text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dd_kpi_ticket_comm_type_value_key UNIQUE (value)
);
GRANT SELECT ON public.dd_kpi_ticket_comm_type TO authenticated;
GRANT ALL    ON public.dd_kpi_ticket_comm_type TO service_role;
ALTER TABLE public.dd_kpi_ticket_comm_type ENABLE ROW LEVEL SECURITY;
CREATE POLICY dd_kpi_ticket_comm_type_select ON public.dd_kpi_ticket_comm_type
  FOR SELECT TO authenticated USING (true);
CREATE POLICY dd_kpi_ticket_comm_type_manage ON public.dd_kpi_ticket_comm_type
  FOR ALL TO authenticated
  USING (public.is_super_admin_safe(auth.uid()))
  WITH CHECK (public.is_super_admin_safe(auth.uid()));
CREATE TRIGGER dd_kpi_ticket_comm_type_updated_at BEFORE UPDATE ON public.dd_kpi_ticket_comm_type
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 8. dd_kpi_metric_status
CREATE TABLE IF NOT EXISTS public.dd_kpi_metric_status (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text        NOT NULL,
  label       text        NOT NULL,
  description text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dd_kpi_metric_status_value_key UNIQUE (value)
);
GRANT SELECT ON public.dd_kpi_metric_status TO authenticated;
GRANT ALL    ON public.dd_kpi_metric_status TO service_role;
ALTER TABLE public.dd_kpi_metric_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY dd_kpi_metric_status_select ON public.dd_kpi_metric_status
  FOR SELECT TO authenticated USING (true);
CREATE POLICY dd_kpi_metric_status_manage ON public.dd_kpi_metric_status
  FOR ALL TO authenticated
  USING (public.is_super_admin_safe(auth.uid()))
  WITH CHECK (public.is_super_admin_safe(auth.uid()));
CREATE TRIGGER dd_kpi_metric_status_updated_at BEFORE UPDATE ON public.dd_kpi_metric_status
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 9. dd_kpi_overall_status
CREATE TABLE IF NOT EXISTS public.dd_kpi_overall_status (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text        NOT NULL,
  label       text        NOT NULL,
  description text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dd_kpi_overall_status_value_key UNIQUE (value)
);
GRANT SELECT ON public.dd_kpi_overall_status TO authenticated;
GRANT ALL    ON public.dd_kpi_overall_status TO service_role;
ALTER TABLE public.dd_kpi_overall_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY dd_kpi_overall_status_select ON public.dd_kpi_overall_status
  FOR SELECT TO authenticated USING (true);
CREATE POLICY dd_kpi_overall_status_manage ON public.dd_kpi_overall_status
  FOR ALL TO authenticated
  USING (public.is_super_admin_safe(auth.uid()))
  WITH CHECK (public.is_super_admin_safe(auth.uid()));
CREATE TRIGGER dd_kpi_overall_status_updated_at BEFORE UPDATE ON public.dd_kpi_overall_status
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 10. dd_kpi_email_type
CREATE TABLE IF NOT EXISTS public.dd_kpi_email_type (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value       text        NOT NULL,
  label       text        NOT NULL,
  description text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dd_kpi_email_type_value_key UNIQUE (value)
);
GRANT SELECT ON public.dd_kpi_email_type TO authenticated;
GRANT ALL    ON public.dd_kpi_email_type TO service_role;
ALTER TABLE public.dd_kpi_email_type ENABLE ROW LEVEL SECURITY;
CREATE POLICY dd_kpi_email_type_select ON public.dd_kpi_email_type
  FOR SELECT TO authenticated USING (true);
CREATE POLICY dd_kpi_email_type_manage ON public.dd_kpi_email_type
  FOR ALL TO authenticated
  USING (public.is_super_admin_safe(auth.uid()))
  WITH CHECK (public.is_super_admin_safe(auth.uid()));
CREATE TRIGGER dd_kpi_email_type_updated_at BEFORE UPDATE ON public.dd_kpi_email_type
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ---------- Seed lookups ----------
INSERT INTO public.dd_kpi_role (value, label, sort_order) VALUES
  ('csc_consultant', 'CSC Consultant', 10),
  ('cst_assistant',  'CST Assistant',  20),
  ('developer',      'Developer',      30)
ON CONFLICT (value) DO NOTHING;

INSERT INTO public.dd_kpi_period_type (value, label, sort_order) VALUES
  ('monthly',   'Monthly',   10),
  ('quarterly', 'Quarterly', 20),
  ('annual',    'Annual',    30)
ON CONFLICT (value) DO NOTHING;

INSERT INTO public.dd_kpi_task_status (value, label, sort_order) VALUES
  ('not_started', 'Not Started', 10),
  ('in_progress', 'In Progress', 20),
  ('completed',   'Completed',   30),
  ('overdue',     'Overdue',     40),
  ('cancelled',   'Cancelled',   50)
ON CONFLICT (value) DO NOTHING;

INSERT INTO public.dd_kpi_ticket_status (value, label, sort_order) VALUES
  ('open',        'Open',        10),
  ('in_progress', 'In Progress', 20),
  ('blocked',     'Blocked',     30),
  ('resolved',    'Resolved',    40),
  ('closed',      'Closed',      50)
ON CONFLICT (value) DO NOTHING;

INSERT INTO public.dd_kpi_ticket_priority (value, label, sort_order) VALUES
  ('low',      'Low',      10),
  ('medium',   'Medium',   20),
  ('high',     'High',     30),
  ('critical', 'Critical', 40)
ON CONFLICT (value) DO NOTHING;

INSERT INTO public.dd_kpi_ticket_platform (value, label, sort_order) VALUES
  ('unicorn',     'Unicorn',     10),
  ('sharepoint',  'SharePoint',  20),
  ('teams',       'Teams',       30),
  ('email',       'Email',       40),
  ('other',       'Other',       90)
ON CONFLICT (value) DO NOTHING;

INSERT INTO public.dd_kpi_ticket_comm_type (value, label, sort_order) VALUES
  ('email',        'Email',         10),
  ('teams_chat',   'Teams Chat',    20),
  ('phone_call',   'Phone Call',    30),
  ('meeting',      'Meeting',       40),
  ('status_update','Status Update', 50)
ON CONFLICT (value) DO NOTHING;

INSERT INTO public.dd_kpi_metric_status (value, label, sort_order) VALUES
  ('green', 'Green', 10),
  ('amber', 'Amber', 20),
  ('red',   'Red',   30)
ON CONFLICT (value) DO NOTHING;

INSERT INTO public.dd_kpi_overall_status (value, label, sort_order) VALUES
  ('exceeds',  'Exceeds',         10),
  ('on_track', 'On Track',        20),
  ('at_risk',  'At Risk',         30),
  ('off_track','Off Track',       40)
ON CONFLICT (value) DO NOTHING;

INSERT INTO public.dd_kpi_email_type (value, label, description, sort_order) VALUES
  ('general_email',  'General Email',  'CST SLA 1 — all non-client emails',         10),
  ('client_message', 'Client Message', 'CST SLA 2 — messages from tenant contacts', 20)
ON CONFLICT (value) DO NOTHING;

-- ---------- Column additions ----------

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS kpi_role text;

ALTER TABLE public.users
  DROP CONSTRAINT IF EXISTS users_kpi_role_fkey;

ALTER TABLE public.users
  ADD CONSTRAINT users_kpi_role_fkey
  FOREIGN KEY (kpi_role) REFERENCES public.dd_kpi_role(value)
  ON UPDATE CASCADE ON DELETE SET NULL
  NOT VALID;

ALTER TABLE public.users
  VALIDATE CONSTRAINT users_kpi_role_fkey;

COMMENT ON COLUMN public.users.kpi_role IS
  'Optional KPI module role assignment (csc_consultant / cst_assistant / developer). Independent of unicorn_role.';

ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS churned_at timestamptz;

COMMENT ON COLUMN public.tenants.churned_at IS
  'Timestamp when tenant was officially marked churned. NULL = not churned. Set in conjunction with lifecycle_status = ''churned''.';

-- ---------- Extend audit trigger to capture kpi_role changes ----------

CREATE OR REPLACE FUNCTION public.fn_audit_users()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  v_action text;
  v_target uuid;
  v_actor  uuid;
  v_tenant bigint;
  v_old    jsonb;
  v_new    jsonb;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_action := 'user_profile_created';
    v_target := NEW.user_uuid;
    v_actor  := auth.uid();
    v_tenant := NEW.tenant_id;
    v_new := jsonb_build_object(
      'first_name', NEW.first_name,
      'last_name', NEW.last_name,
      'email', NEW.email,
      'global_role', NEW.global_role,
      'unicorn_role', NEW.unicorn_role,
      'superadmin_level', NEW.superadmin_level,
      'archived', NEW.archived,
      'disabled', NEW.disabled,
      'tenant_id', NEW.tenant_id,
      'is_csc', NEW.is_csc,
      'is_vivacity_internal', NEW.is_vivacity_internal,
      'kpi_role', NEW.kpi_role
    );
  ELSIF TG_OP = 'UPDATE' THEN
    v_action := 'user_profile_updated';
    v_target := COALESCE(NEW.user_uuid, OLD.user_uuid);
    v_actor  := auth.uid();
    v_tenant := COALESCE(NEW.tenant_id, OLD.tenant_id);
    v_old := jsonb_build_object(
      'first_name', OLD.first_name,
      'last_name', OLD.last_name,
      'email', OLD.email,
      'global_role', OLD.global_role,
      'unicorn_role', OLD.unicorn_role,
      'superadmin_level', OLD.superadmin_level,
      'archived', OLD.archived,
      'disabled', OLD.disabled,
      'tenant_id', OLD.tenant_id,
      'is_csc', OLD.is_csc,
      'is_vivacity_internal', OLD.is_vivacity_internal,
      'kpi_role', OLD.kpi_role
    );
    v_new := jsonb_build_object(
      'first_name', NEW.first_name,
      'last_name', NEW.last_name,
      'email', NEW.email,
      'global_role', NEW.global_role,
      'unicorn_role', NEW.unicorn_role,
      'superadmin_level', NEW.superadmin_level,
      'archived', NEW.archived,
      'disabled', NEW.disabled,
      'tenant_id', NEW.tenant_id,
      'is_csc', NEW.is_csc,
      'is_vivacity_internal', NEW.is_vivacity_internal,
      'kpi_role', NEW.kpi_role
    );
  ELSIF TG_OP = 'DELETE' THEN
    v_action := 'user_profile_deleted';
    v_target := OLD.user_uuid;
    v_actor  := auth.uid();
    v_tenant := OLD.tenant_id;
    v_old := jsonb_build_object(
      'first_name', OLD.first_name,
      'last_name', OLD.last_name,
      'email', OLD.email,
      'global_role', OLD.global_role,
      'unicorn_role', OLD.unicorn_role,
      'superadmin_level', OLD.superadmin_level,
      'archived', OLD.archived,
      'disabled', OLD.disabled,
      'tenant_id', OLD.tenant_id,
      'is_csc', OLD.is_csc,
      'is_vivacity_internal', OLD.is_vivacity_internal,
      'kpi_role', OLD.kpi_role
    );
  END IF;

  INSERT INTO public.audit_user_events (
    actor_user_uuid, target_user_uuid, action, tenant_id, details
  ) VALUES (
    v_actor,
    v_target,
    v_action,
    v_tenant,
    jsonb_strip_nulls(jsonb_build_object('old', v_old, 'new', v_new))
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  ELSE
    RETURN NEW;
  END IF;
END;
$function$;

-- Recreate UPDATE trigger to add kpi_role to the WHEN clause.
DROP TRIGGER IF EXISTS trg_audit_users_update ON public.users;
CREATE TRIGGER trg_audit_users_update
  AFTER UPDATE ON public.users
  FOR EACH ROW
  WHEN (
    (old.first_name IS DISTINCT FROM new.first_name)
    OR (old.last_name IS DISTINCT FROM new.last_name)
    OR (old.email IS DISTINCT FROM new.email)
    OR (old.global_role IS DISTINCT FROM new.global_role)
    OR (old.unicorn_role IS DISTINCT FROM new.unicorn_role)
    OR (old.superadmin_level IS DISTINCT FROM new.superadmin_level)
    OR (old.archived IS DISTINCT FROM new.archived)
    OR (old.disabled IS DISTINCT FROM new.disabled)
    OR (old.tenant_id IS DISTINCT FROM new.tenant_id)
    OR (old.is_csc IS DISTINCT FROM new.is_csc)
    OR (old.is_vivacity_internal IS DISTINCT FROM new.is_vivacity_internal)
    OR (old.kpi_role IS DISTINCT FROM new.kpi_role)
  )
  EXECUTE FUNCTION public.fn_audit_users();

-- ---------- RLS helper: is_kpi_reviewer_safe ----------
-- user_roles uses (user_uuid uuid, role text) per schema inspection.

CREATE OR REPLACE FUNCTION public.is_kpi_reviewer_safe(_uid uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_uuid = _uid
      AND role = 'kpi_reviewer'
      AND (expires_at IS NULL OR expires_at > now())
  )
$$;

REVOKE ALL ON FUNCTION public.is_kpi_reviewer_safe(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_kpi_reviewer_safe(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_kpi_reviewer_safe(uuid) TO service_role;