-- =============================================================
-- Cross-Tenant Cohort Access Sender — schema (DDL only)
-- Staff-only queued bulk Activate / Send password reset.
-- Reuses activate-ghost-user and send-password-reset unchanged.
-- =============================================================

-- 1. Account-state view (SECURITY DEFINER consumers only — not granted to anon/authenticated).
CREATE OR REPLACE VIEW public.v_auth_user_state AS
SELECT
  u.user_uuid,
  u.email,
  u.tenant_id,
  u.unicorn_role,
  u.user_type,
  u.disabled,
  au.id IS NULL                           AS is_ghost,
  au.last_sign_in_at,
  au.created_at                           AS auth_created_at,
  CASE
    WHEN u.disabled IS TRUE                                   THEN 'disabled'
    WHEN au.id IS NULL                                        THEN 'ghost'
    WHEN au.last_sign_in_at IS NULL                           THEN 'invited'
    WHEN au.last_sign_in_at >= now() - interval '90 days'     THEN 'active'
    ELSE 'dormant'
  END AS account_state
FROM public.users u
LEFT JOIN auth.users au ON au.id = u.user_uuid;

REVOKE ALL ON public.v_auth_user_state FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.v_auth_user_state TO service_role;

-- 2. Jobs table
CREATE TABLE public.cohort_send_jobs (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_by            uuid NOT NULL,
  action                text NOT NULL CHECK (action IN ('activate','reset')),
  filter_json           jsonb NOT NULL DEFAULT '{}'::jsonb,
  status                text NOT NULL DEFAULT 'running'
                        CHECK (status IN ('draft','running','paused','completed','cancelled','failed','stalled')),
  cap                   int  NOT NULL DEFAULT 1000 CHECK (cap > 0 AND cap <= 1000),
  batch_size            int  NOT NULL DEFAULT 10  CHECK (batch_size > 0 AND batch_size <= 50),
  throttle_ms           int  NOT NULL DEFAULT 400 CHECK (throttle_ms >= 0 AND throttle_ms <= 5000),
  total_resolved        int  NOT NULL DEFAULT 0,
  total_planned         int  NOT NULL DEFAULT 0,
  total_sent            int  NOT NULL DEFAULT 0,
  total_skipped         int  NOT NULL DEFAULT 0,
  total_failed          int  NOT NULL DEFAULT 0,
  consecutive_failures  int  NOT NULL DEFAULT 0,
  notes                 text,
  started_at            timestamptz,
  finished_at           timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.cohort_send_jobs TO authenticated;
GRANT ALL    ON public.cohort_send_jobs TO service_role;

ALTER TABLE public.cohort_send_jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Vivacity staff can view cohort jobs"
ON public.cohort_send_jobs FOR SELECT TO authenticated
USING (public.is_vivacity_staff(auth.uid()));

CREATE POLICY "Service role full access to cohort jobs"
ON public.cohort_send_jobs FOR ALL TO service_role
USING (true) WITH CHECK (true);

CREATE TRIGGER trg_cohort_send_jobs_updated_at
BEFORE UPDATE ON public.cohort_send_jobs
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 3. Items table
CREATE TABLE public.cohort_send_job_items (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id          uuid NOT NULL REFERENCES public.cohort_send_jobs(id) ON DELETE CASCADE,
  user_uuid       uuid NOT NULL,
  tenant_id       bigint,
  email           text,
  state_snapshot  text NOT NULL,
  planned_action  text NOT NULL CHECK (planned_action IN ('activate','reset','skip')),
  skip_reason     text,
  outcome         text NOT NULL DEFAULT 'pending'
                  CHECK (outcome IN ('pending','sent','skipped','failed')),
  reason          text,
  attempts        int  NOT NULL DEFAULT 0,
  locked_at       timestamptz,
  locked_by       text,
  processed_at    timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cohort_send_job_items_unique UNIQUE (job_id, user_uuid)
);

CREATE INDEX cohort_send_job_items_job_outcome_idx
  ON public.cohort_send_job_items (job_id, outcome);

CREATE INDEX cohort_send_job_items_pending_lock_idx
  ON public.cohort_send_job_items (job_id, locked_at)
  WHERE outcome = 'pending';

GRANT SELECT ON public.cohort_send_job_items TO authenticated;
GRANT ALL    ON public.cohort_send_job_items TO service_role;

ALTER TABLE public.cohort_send_job_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Vivacity staff can view cohort job items"
ON public.cohort_send_job_items FOR SELECT TO authenticated
USING (public.is_vivacity_staff(auth.uid()));

CREATE POLICY "Service role full access to cohort job items"
ON public.cohort_send_job_items FOR ALL TO service_role
USING (true) WITH CHECK (true);

-- =============================================================
-- 4. RPCs (SECURITY DEFINER with pinned search_path)
-- =============================================================

-- 4a. resolve_cohort — returns the planned recipient list given a filter.
CREATE OR REPLACE FUNCTION public.resolve_cohort(
  p_filter jsonb,
  p_cap    int DEFAULT 1000
)
RETURNS TABLE (
  user_uuid       uuid,
  email           text,
  tenant_id       bigint,
  tenant_name     text,
  account_state   text,
  unicorn_role    text,
  last_sign_in_at timestamptz,
  truncated       boolean
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_states           text[]  := NULL;
  v_tenant_ids       bigint[] := NULL;
  v_roles            text[]  := NULL;
  v_tiers            text[]  := NULL;
  v_membership_status text[] := NULL;
  v_membership_state  text[] := NULL;
  v_lsi_mode         text;
  v_lsi_before       timestamptz;
  v_lsi_from         timestamptz;
  v_lsi_to           timestamptz;
  v_uc_mode          text;
  v_uc_before        timestamptz;
  v_uc_from          timestamptz;
  v_uc_to            timestamptz;
  v_total            int;
BEGIN
  IF NOT public.is_vivacity_staff(auth.uid()) THEN
    RAISE EXCEPTION 'FORBIDDEN: Vivacity staff only';
  END IF;

  IF p_cap IS NULL OR p_cap <= 0 THEN p_cap := 1000; END IF;
  IF p_cap > 1000 THEN p_cap := 1000; END IF;

  -- Optional filter extraction
  IF jsonb_typeof(p_filter->'account_state') = 'array' THEN
    SELECT array_agg(value::text) INTO v_states
    FROM jsonb_array_elements_text(p_filter->'account_state');
  END IF;
  IF jsonb_typeof(p_filter->'tenant_ids') = 'array' THEN
    SELECT array_agg((value)::bigint) INTO v_tenant_ids
    FROM jsonb_array_elements_text(p_filter->'tenant_ids');
  END IF;
  IF jsonb_typeof(p_filter->'roles') = 'array' THEN
    SELECT array_agg(value::text) INTO v_roles
    FROM jsonb_array_elements_text(p_filter->'roles');
  END IF;
  IF jsonb_typeof(p_filter->'complyhub_tier') = 'array' THEN
    SELECT array_agg(value::text) INTO v_tiers
    FROM jsonb_array_elements_text(p_filter->'complyhub_tier');
  END IF;
  IF jsonb_typeof(p_filter->'membership_status') = 'array' THEN
    SELECT array_agg(value::text) INTO v_membership_status
    FROM jsonb_array_elements_text(p_filter->'membership_status');
  END IF;
  IF jsonb_typeof(p_filter->'membership_state') = 'array' THEN
    SELECT array_agg(value::text) INTO v_membership_state
    FROM jsonb_array_elements_text(p_filter->'membership_state');
  END IF;

  v_lsi_mode   := nullif(p_filter#>>'{last_sign_in,mode}','');
  v_lsi_before := nullif(p_filter#>>'{last_sign_in,before}','')::timestamptz;
  v_lsi_from   := nullif(p_filter#>>'{last_sign_in,from}','')::timestamptz;
  v_lsi_to     := nullif(p_filter#>>'{last_sign_in,to}','')::timestamptz;

  v_uc_mode    := nullif(p_filter#>>'{user_created,mode}','');
  v_uc_before  := nullif(p_filter#>>'{user_created,before}','')::timestamptz;
  v_uc_from    := nullif(p_filter#>>'{user_created,from}','')::timestamptz;
  v_uc_to      := nullif(p_filter#>>'{user_created,to}','')::timestamptz;

  RETURN QUERY
  WITH base AS (
    SELECT
      s.user_uuid,
      s.email,
      s.tenant_id,
      t.name AS tenant_name,
      s.account_state,
      s.unicorn_role,
      s.last_sign_in_at,
      s.auth_created_at
    FROM public.v_auth_user_state s
    LEFT JOIN public.tenants t ON t.id = s.tenant_id
    WHERE s.email IS NOT NULL
      AND (v_states IS NULL OR s.account_state = ANY(v_states))
      AND (v_tenant_ids IS NULL OR s.tenant_id = ANY(v_tenant_ids))
      AND (v_roles IS NULL OR s.unicorn_role = ANY(v_roles))
      AND (v_tiers IS NULL OR t.complyhub_membership_tier = ANY(v_tiers))
      AND (
        v_lsi_mode IS NULL
        OR (v_lsi_mode = 'never'   AND s.last_sign_in_at IS NULL)
        OR (v_lsi_mode = 'before'  AND s.last_sign_in_at IS NOT NULL AND s.last_sign_in_at < v_lsi_before)
        OR (v_lsi_mode = 'between' AND s.last_sign_in_at IS NOT NULL AND s.last_sign_in_at BETWEEN v_lsi_from AND v_lsi_to)
      )
      AND (
        v_uc_mode IS NULL
        OR (v_uc_mode = 'before'  AND s.auth_created_at IS NOT NULL AND s.auth_created_at < v_uc_before)
        OR (v_uc_mode = 'between' AND s.auth_created_at IS NOT NULL AND s.auth_created_at BETWEEN v_uc_from AND v_uc_to)
      )
      AND (
        v_membership_status IS NULL
        OR EXISTS (
          SELECT 1 FROM public.tenant_compliance_memberships m
          WHERE m.tenant_id = s.tenant_id AND m.status = ANY(v_membership_status)
        )
      )
      AND (
        v_membership_state IS NULL
        OR EXISTS (
          SELECT 1 FROM public.membership_entitlements me
          WHERE me.tenant_id = s.tenant_id AND me.membership_state = ANY(v_membership_state)
        )
      )
  ),
  counted AS (
    SELECT count(*)::int AS n FROM base
  )
  SELECT
    b.user_uuid,
    b.email,
    b.tenant_id,
    b.tenant_name,
    b.account_state,
    b.unicorn_role,
    b.last_sign_in_at,
    ((SELECT n FROM counted) > p_cap) AS truncated
  FROM base b
  ORDER BY b.tenant_id NULLS LAST, b.email
  LIMIT p_cap;
END;
$$;

REVOKE ALL    ON FUNCTION public.resolve_cohort(jsonb,int) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.resolve_cohort(jsonb,int) TO authenticated;

-- 4b. launch_cohort_job — creates the job + items in one transaction.
-- planned_action is derived from state via the routing matrix.
CREATE OR REPLACE FUNCTION public.launch_cohort_job(
  p_action      text,
  p_filter      jsonb,
  p_cap         int  DEFAULT 1000,
  p_batch_size  int  DEFAULT 10,
  p_throttle_ms int  DEFAULT 400,
  p_notes       text DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_job_id uuid;
  v_caller uuid := auth.uid();
  v_resolved int;
  v_planned  int;
BEGIN
  IF NOT public.is_vivacity_staff(v_caller) THEN
    RAISE EXCEPTION 'FORBIDDEN: Vivacity staff only';
  END IF;
  IF p_action NOT IN ('activate','reset') THEN
    RAISE EXCEPTION 'INVALID_ACTION: must be activate or reset';
  END IF;

  INSERT INTO public.cohort_send_jobs (
    created_by, action, filter_json, cap, batch_size, throttle_ms, notes, started_at, status
  ) VALUES (
    v_caller, p_action, COALESCE(p_filter,'{}'::jsonb),
    LEAST(GREATEST(COALESCE(p_cap,1000),1),1000),
    LEAST(GREATEST(COALESCE(p_batch_size,10),1),50),
    LEAST(GREATEST(COALESCE(p_throttle_ms,400),0),5000),
    p_notes, now(), 'running'
  )
  RETURNING id INTO v_job_id;

  WITH resolved AS (
    SELECT * FROM public.resolve_cohort(p_filter, LEAST(GREATEST(COALESCE(p_cap,1000),1),1000))
  ),
  ins AS (
    INSERT INTO public.cohort_send_job_items (
      job_id, user_uuid, tenant_id, email, state_snapshot, planned_action, skip_reason, outcome, reason, processed_at
    )
    SELECT
      v_job_id,
      r.user_uuid,
      r.tenant_id,
      r.email,
      r.account_state,
      CASE
        WHEN r.account_state = 'disabled' THEN 'skip'
        WHEN r.account_state = 'ghost'    AND p_action = 'activate' THEN 'activate'
        WHEN r.account_state = 'ghost'    AND p_action = 'reset'    THEN 'skip'
        WHEN r.account_state IN ('invited','active','dormant') AND p_action = 'reset' THEN 'reset'
        WHEN r.account_state IN ('invited','active','dormant') AND p_action = 'activate' THEN 'skip'
        ELSE 'skip'
      END AS planned_action,
      CASE
        WHEN r.account_state = 'disabled' THEN 'Account disabled — re-enable first'
        WHEN r.account_state = 'ghost' AND p_action = 'reset' THEN 'No auth account yet — use Activate'
        WHEN r.account_state IN ('invited','active','dormant') AND p_action = 'activate' THEN 'Already activated — use Send password reset'
        ELSE NULL
      END AS skip_reason,
      CASE WHEN r.account_state = 'disabled' THEN 'skipped'
           WHEN r.account_state = 'ghost'    AND p_action = 'reset'    THEN 'skipped'
           WHEN r.account_state IN ('invited','active','dormant') AND p_action = 'activate' THEN 'skipped'
           ELSE 'pending'
      END AS outcome,
      CASE
        WHEN r.account_state = 'disabled' THEN 'Account disabled — re-enable first'
        WHEN r.account_state = 'ghost' AND p_action = 'reset' THEN 'No auth account yet — use Activate'
        WHEN r.account_state IN ('invited','active','dormant') AND p_action = 'activate' THEN 'Already activated — use Send password reset'
        ELSE NULL
      END AS reason,
      CASE WHEN r.account_state = 'disabled'
            OR (r.account_state = 'ghost' AND p_action = 'reset')
            OR (r.account_state IN ('invited','active','dormant') AND p_action = 'activate')
           THEN now() ELSE NULL END AS processed_at
    FROM resolved r
    ON CONFLICT (job_id, user_uuid) DO NOTHING
    RETURNING outcome
  )
  SELECT count(*) FILTER (WHERE outcome = 'pending'),
         count(*)
  INTO v_planned, v_resolved
  FROM ins;

  UPDATE public.cohort_send_jobs
  SET total_resolved = v_resolved,
      total_planned  = v_planned,
      total_skipped  = v_resolved - v_planned
  WHERE id = v_job_id;

  -- Single audit row at launch
  INSERT INTO public.audit_eos_events (
    user_id, entity, entity_id, action, reason, details
  ) VALUES (
    v_caller, 'cohort_send_job', v_job_id, 'cohort_job_launched',
    'Cross-tenant cohort access sender launched',
    jsonb_build_object('action', p_action, 'resolved', v_resolved, 'planned', v_planned, 'filter', p_filter)
  );

  RETURN v_job_id;
END;
$$;

REVOKE ALL    ON FUNCTION public.launch_cohort_job(text,jsonb,int,int,int,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.launch_cohort_job(text,jsonb,int,int,int,text) TO authenticated;

-- 4c. lease_cohort_job_items — atomically claim a chunk of pending items.
CREATE OR REPLACE FUNCTION public.lease_cohort_job_items(
  p_job_id    uuid,
  p_worker_id text,
  p_limit     int DEFAULT 10
)
RETURNS TABLE (
  id             bigint,
  user_uuid      uuid,
  tenant_id      bigint,
  email          text,
  planned_action text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  IF NOT public.is_vivacity_staff(auth.uid()) THEN
    RAISE EXCEPTION 'FORBIDDEN: Vivacity staff only';
  END IF;

  -- Stop if job not running
  IF NOT EXISTS (
    SELECT 1 FROM public.cohort_send_jobs
    WHERE id = p_job_id AND status = 'running'
  ) THEN
    RETURN;
  END IF;

  RETURN QUERY
  UPDATE public.cohort_send_job_items it
  SET locked_at = now(),
      locked_by = p_worker_id,
      attempts  = it.attempts + 1
  WHERE it.id IN (
    SELECT i.id
    FROM public.cohort_send_job_items i
    WHERE i.job_id = p_job_id
      AND i.outcome = 'pending'
      AND (i.locked_at IS NULL OR i.locked_at < now() - interval '5 minutes')
    ORDER BY i.id
    LIMIT GREATEST(LEAST(COALESCE(p_limit,10),50),1)
    FOR UPDATE SKIP LOCKED
  )
  RETURNING it.id, it.user_uuid, it.tenant_id, it.email, it.planned_action;
END;
$$;

REVOKE ALL    ON FUNCTION public.lease_cohort_job_items(uuid,text,int) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.lease_cohort_job_items(uuid,text,int) TO authenticated;

-- 4d. record_cohort_item_outcome — finalise one item and bump job counters.
CREATE OR REPLACE FUNCTION public.record_cohort_item_outcome(
  p_item_id bigint,
  p_outcome text,
  p_reason  text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_job_id uuid;
BEGIN
  IF NOT public.is_vivacity_staff(auth.uid()) THEN
    RAISE EXCEPTION 'FORBIDDEN: Vivacity staff only';
  END IF;
  IF p_outcome NOT IN ('sent','skipped','failed') THEN
    RAISE EXCEPTION 'INVALID_OUTCOME';
  END IF;

  UPDATE public.cohort_send_job_items
  SET outcome      = p_outcome,
      reason       = p_reason,
      processed_at = now(),
      locked_at    = NULL,
      locked_by    = NULL
  WHERE id = p_item_id AND outcome = 'pending'
  RETURNING job_id INTO v_job_id;

  IF v_job_id IS NULL THEN
    RETURN;
  END IF;

  UPDATE public.cohort_send_jobs
  SET total_sent    = total_sent    + CASE WHEN p_outcome = 'sent'    THEN 1 ELSE 0 END,
      total_skipped = total_skipped + CASE WHEN p_outcome = 'skipped' THEN 1 ELSE 0 END,
      total_failed  = total_failed  + CASE WHEN p_outcome = 'failed'  THEN 1 ELSE 0 END,
      consecutive_failures = CASE WHEN p_outcome = 'failed' THEN consecutive_failures + 1 ELSE 0 END
  WHERE id = v_job_id;
END;
$$;

REVOKE ALL    ON FUNCTION public.record_cohort_item_outcome(bigint,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.record_cohort_item_outcome(bigint,text,text) TO authenticated;

-- 4e. finalise_cohort_job — moves a job to completed when nothing pending remains.
CREATE OR REPLACE FUNCTION public.finalise_cohort_job(p_job_id uuid)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_pending int;
  v_status  text;
  v_action  text;
  v_caller  uuid := auth.uid();
BEGIN
  IF NOT public.is_vivacity_staff(v_caller) THEN
    RAISE EXCEPTION 'FORBIDDEN: Vivacity staff only';
  END IF;

  SELECT count(*) INTO v_pending
  FROM public.cohort_send_job_items
  WHERE job_id = p_job_id AND outcome = 'pending';

  SELECT status, action INTO v_status, v_action
  FROM public.cohort_send_jobs WHERE id = p_job_id;

  IF v_pending = 0 AND v_status = 'running' THEN
    UPDATE public.cohort_send_jobs
    SET status = 'completed', finished_at = now()
    WHERE id = p_job_id;

    INSERT INTO public.audit_eos_events (
      user_id, entity, entity_id, action, reason, details
    )
    SELECT v_caller, 'cohort_send_job', id, 'cohort_job_completed',
           'Cross-tenant cohort access sender completed',
           jsonb_build_object('action', v_action,
                              'sent', total_sent,
                              'skipped', total_skipped,
                              'failed', total_failed)
    FROM public.cohort_send_jobs WHERE id = p_job_id;

    RETURN 'completed';
  END IF;
  RETURN v_status;
END;
$$;

REVOKE ALL    ON FUNCTION public.finalise_cohort_job(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.finalise_cohort_job(uuid) TO authenticated;

-- 4f. set_cohort_job_status — staff Pause / Resume / Cancel.
CREATE OR REPLACE FUNCTION public.set_cohort_job_status(
  p_job_id uuid,
  p_status text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  IF NOT public.is_vivacity_staff(auth.uid()) THEN
    RAISE EXCEPTION 'FORBIDDEN: Vivacity staff only';
  END IF;
  IF p_status NOT IN ('running','paused','cancelled') THEN
    RAISE EXCEPTION 'INVALID_STATUS';
  END IF;

  UPDATE public.cohort_send_jobs
  SET status = p_status,
      finished_at = CASE WHEN p_status = 'cancelled' THEN now() ELSE finished_at END,
      consecutive_failures = CASE WHEN p_status = 'running' THEN 0 ELSE consecutive_failures END
  WHERE id = p_job_id
    AND status IN ('running','paused');
END;
$$;

REVOKE ALL    ON FUNCTION public.set_cohort_job_status(uuid,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_cohort_job_status(uuid,text) TO authenticated;

-- 4g. reclaim_stale_cohort_locks — pg_cron maintenance (NO sends).
CREATE OR REPLACE FUNCTION public.reclaim_stale_cohort_locks()
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count int;
BEGIN
  UPDATE public.cohort_send_job_items
  SET locked_at = NULL, locked_by = NULL
  WHERE outcome = 'pending'
    AND locked_at IS NOT NULL
    AND locked_at < now() - interval '5 minutes';
  GET DIAGNOSTICS v_count = ROW_COUNT;

  -- Mark jobs as stalled when running for >2h without progress and >0 pending.
  UPDATE public.cohort_send_jobs j
  SET status = 'stalled'
  WHERE j.status = 'running'
    AND j.started_at < now() - interval '2 hours'
    AND EXISTS (SELECT 1 FROM public.cohort_send_job_items i WHERE i.job_id = j.id AND i.outcome = 'pending')
    AND NOT EXISTS (SELECT 1 FROM public.cohort_send_job_items i WHERE i.job_id = j.id AND i.processed_at > now() - interval '15 minutes');

  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION public.reclaim_stale_cohort_locks() FROM PUBLIC, anon, authenticated;

-- pg_cron maintenance (DDL-equivalent: cron schedule via cron.schedule).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname='pg_cron') THEN
    PERFORM cron.unschedule('reclaim-stale-cohort-locks')
    WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname='reclaim-stale-cohort-locks');
    PERFORM cron.schedule(
      'reclaim-stale-cohort-locks',
      '*/5 * * * *',
      $cron$ SELECT public.reclaim_stale_cohort_locks(); $cron$
    );
  END IF;
END$$;

NOTIFY pgrst, 'reload schema';