-- Drop existing empty table
DROP TABLE IF EXISTS public.document_instances;

-- Recreate with bigint id and proper structure
CREATE TABLE public.document_instances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id bigint NOT NULL,
  stage_instance_id bigint,
  tenant_id bigint,
  is_generated boolean DEFAULT false,
  generation_date timestamptz,
  status text,
  notes text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Add RLS
ALTER TABLE public.document_instances ENABLE ROW LEVEL SECURITY;

-- Add index on stage_instance_id for efficient joins
CREATE INDEX idx_document_instances_stage_instance 
  ON public.document_instances(stage_instance_id);

-- Add index on tenant_id
CREATE INDEX idx_document_instances_tenant 
  ON public.document_instances(tenant_id);