-- =====================================================================
-- Migration: user_type_enum  ->  public.dd_user_type lookup table
-- Single transaction. Aborts on any pre- or post-flight assertion failure.
-- Legacy enum public.user_type_enum is RETAINED (archive.backup_users dep).
--
-- ORDERING NOTE: the 4 affected RLS policies are dropped BEFORE the
-- ALTER COLUMN ... TYPE text (Postgres refuses to alter a column type
-- while a policy depends on it). They are recreated immediately after
-- the FK is added, with byte-identical logic minus the ::user_type_enum
-- casts.
-- =====================================================================

-- ---------------------------------------------------------------------
-- STEP 1 — PRE-FLIGHT ASSERTIONS
-- ---------------------------------------------------------------------
DO $preflight$
DECLARE
  v_total            bigint;
  v_nulls            bigint;
  v_invalid          bigint;
  v_client_parent    bigint;
  v_client_child     bigint;
  v_vivacity_team    bigint;
  v_vivacity         bigint;
  v_client           bigint;
  v_member           bigint;
  v_enum_label_count bigint;
  v_archive_dep      bigint;
BEGIN
  SELECT count(*) INTO v_total FROM public.users;
  IF v_total <> 502 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL: public.users row count = %, expected 502', v_total;
  END IF;

  SELECT count(*) INTO v_nulls FROM public.users WHERE user_type IS NULL;
  IF v_nulls <> 0 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL: public.users has % NULL user_type rows, expected 0', v_nulls;
  END IF;

  SELECT count(*) INTO v_invalid
  FROM public.users
  WHERE user_type::text NOT IN
    ('Vivacity','Client','Member','Client Parent','Client Child','Vivacity Team');
  IF v_invalid <> 0 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL: % users have user_type outside the 6 known labels', v_invalid;
  END IF;

  SELECT
    count(*) FILTER (WHERE user_type::text = 'Client Parent'),
    count(*) FILTER (WHERE user_type::text = 'Client Child'),
    count(*) FILTER (WHERE user_type::text = 'Vivacity Team'),
    count(*) FILTER (WHERE user_type::text = 'Vivacity'),
    count(*) FILTER (WHERE user_type::text = 'Client'),
    count(*) FILTER (WHERE user_type::text = 'Member')
  INTO v_client_parent, v_client_child, v_vivacity_team,
       v_vivacity,      v_client,       v_member
  FROM public.users;

  IF v_client_parent <> 417 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL: Client Parent = %, expected 417', v_client_parent;
  END IF;
  IF v_client_child <> 62 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL: Client Child = %, expected 62', v_client_child;
  END IF;
  IF v_vivacity_team <> 23 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL: Vivacity Team = %, expected 23', v_vivacity_team;
  END IF;
  IF v_vivacity <> 0 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL: Vivacity = %, expected 0', v_vivacity;
  END IF;
  IF v_client <> 0 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL: Client = %, expected 0', v_client;
  END IF;
  IF v_member <> 0 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL: Member = %, expected 0', v_member;
  END IF;

  SELECT count(*) INTO v_enum_label_count
  FROM pg_enum e
  JOIN pg_type t ON t.oid = e.enumtypid
  JOIN pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'public'
    AND t.typname = 'user_type_enum'
    AND e.enumlabel IN ('Vivacity','Client','Member','Client Parent','Client Child','Vivacity Team');
  IF v_enum_label_count <> 6 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL: public.user_type_enum missing one of the 6 expected labels (found %)', v_enum_label_count;
  END IF;

  SELECT count(*) INTO v_archive_dep
  FROM information_schema.columns
  WHERE table_schema = 'archive'
    AND table_name   = 'backup_users'
    AND udt_schema   = 'public'
    AND udt_name     = 'user_type_enum';
  IF v_archive_dep < 1 THEN
    RAISE NOTICE 'PRE-FLIGHT INFO: archive.backup_users no longer references user_type_enum (cleanup may already be done).';
  ELSE
    RAISE NOTICE 'PRE-FLIGHT INFO: archive.backup_users still references user_type_enum — enum will be retained.';
  END IF;

  RAISE NOTICE 'PRE-FLIGHT PASSED.';
END
$preflight$;

-- ---------------------------------------------------------------------
-- STEP 2 — CREATE dd_user_type TABLE
-- ---------------------------------------------------------------------
CREATE TABLE public.dd_user_type (
  id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value      text        NOT NULL,
  label      text        NOT NULL,
  sort_order integer     NOT NULL DEFAULT 0,
  is_active  boolean     NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dd_user_type_value_key UNIQUE (value)
);

-- ---------------------------------------------------------------------
-- STEP 3 — SEED 6 VALUES (byte-identical to enum labels)
-- ---------------------------------------------------------------------
INSERT INTO public.dd_user_type (value, label, sort_order, is_active) VALUES
  ('Vivacity',      'Vivacity',      10, true),
  ('Vivacity Team', 'Vivacity Team', 20, true),
  ('Client',        'Client',        30, true),
  ('Client Parent', 'Client Parent', 40, true),
  ('Client Child',  'Client Child',  50, true),
  ('Member',        'Member',        60, true);

-- ---------------------------------------------------------------------
-- STEP 4 — RLS on dd_user_type (publicly readable; no write policy)
-- ---------------------------------------------------------------------
ALTER TABLE public.dd_user_type ENABLE ROW LEVEL SECURITY;

CREATE POLICY dd_user_type_read ON public.dd_user_type
  FOR SELECT TO public
  USING (true);

-- ---------------------------------------------------------------------
-- STEP 5a — DROP the 4 dependent RLS policies (so we can ALTER the column)
-- ---------------------------------------------------------------------
DROP POLICY IF EXISTS tasks_tenants_tenant_select ON public.tasks_tenants;
DROP POLICY IF EXISTS tasks_tenants_tenant_update ON public.tasks_tenants;
DROP POLICY IF EXISTS eos_agenda_template_versions_admin_insert ON public.eos_agenda_template_versions;
DROP POLICY IF EXISTS eos_agenda_template_versions_admin_update ON public.eos_agenda_template_versions;

-- ---------------------------------------------------------------------
-- STEP 5b — CONVERT users.user_type FROM ENUM TO TEXT + FK
-- ---------------------------------------------------------------------
ALTER TABLE public.users
  ALTER COLUMN user_type TYPE text USING user_type::text;

ALTER TABLE public.users
  ADD CONSTRAINT users_user_type_fkey
  FOREIGN KEY (user_type)
  REFERENCES public.dd_user_type(value)
  ON UPDATE CASCADE
  ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_users_user_type ON public.users(user_type);

-- ---------------------------------------------------------------------
-- STEP 6 — RE-CREATE 4 RLS POLICIES (cast removal only; logic byte-identical)
-- ---------------------------------------------------------------------
CREATE POLICY tasks_tenants_tenant_select ON public.tasks_tenants
  FOR SELECT TO authenticated
  USING (
    (tenant_id = (SELECT users.tenant_id FROM users WHERE users.user_uuid = (SELECT auth.uid())))
    AND ((SELECT users.user_type FROM users WHERE users.user_uuid = (SELECT auth.uid())) = ANY (ARRAY['Client Parent', 'Client Child']))
  );

CREATE POLICY tasks_tenants_tenant_update ON public.tasks_tenants
  FOR UPDATE TO authenticated
  USING (
    (tenant_id = (SELECT users.tenant_id FROM users WHERE users.user_uuid = (SELECT auth.uid())))
    AND ((SELECT users.user_type FROM users WHERE users.user_uuid = (SELECT auth.uid())) = ANY (ARRAY['Client Parent', 'Client Child']))
  )
  WITH CHECK (
    (tenant_id = (SELECT users.tenant_id FROM users WHERE users.user_uuid = (SELECT auth.uid())))
    AND ((SELECT users.user_type FROM users WHERE users.user_uuid = (SELECT auth.uid())) = ANY (ARRAY['Client Parent', 'Client Child']))
  );

CREATE POLICY eos_agenda_template_versions_admin_insert ON public.eos_agenda_template_versions
  FOR INSERT TO public
  WITH CHECK (
    is_super_admin() OR (EXISTS (
      SELECT 1
      FROM eos_agenda_templates t
      JOIN users u ON u.tenant_id = t.tenant_id
      WHERE t.id = eos_agenda_template_versions.template_id
        AND u.user_uuid = (SELECT auth.uid())
        AND u.user_type = ANY (ARRAY['Vivacity', 'Client', 'Vivacity Team'])
    ))
  );

CREATE POLICY eos_agenda_template_versions_admin_update ON public.eos_agenda_template_versions
  FOR UPDATE TO public
  USING (
    is_super_admin() OR (EXISTS (
      SELECT 1
      FROM eos_agenda_templates t
      JOIN users u ON u.tenant_id = t.tenant_id
      WHERE t.id = eos_agenda_template_versions.template_id
        AND u.user_uuid = (SELECT auth.uid())
        AND u.user_type = ANY (ARRAY['Vivacity', 'Client', 'Vivacity Team'])
    ))
  );

-- ---------------------------------------------------------------------
-- STEP 7 — UPDATE 4 SQL FUNCTIONS (surgical edits only)
-- ---------------------------------------------------------------------

-- 7.1 accept_invitation_v2
CREATE OR REPLACE FUNCTION public.accept_invitation_v2(p_token_hash text, p_user_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_invitation record;
  v_existing_uuid uuid;
  v_existing_accepted boolean;
  v_relationship_role public.tenant_user_role;
  v_tu_role text;
  v_tu_primary boolean;
  v_tu_secondary boolean;
  v_tu_access_scope text;
  v_u_unicorn_role public.unicorn_role;
  v_u_user_type text;
  v_tm_role text;
  v_tm_status text;
  v_is_internal_fallback boolean := false;
BEGIN
  IF p_token_hash IS NULL OR p_user_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'code', 'INVALID_PARAMS', 'message', 'Missing required parameters');
  END IF;

  SELECT * INTO v_invitation
  FROM public.user_invitations
  WHERE token_hash = p_token_hash
    AND status = 'pending';

  IF v_invitation IS NULL THEN
    SELECT EXISTS (
      SELECT 1 FROM public.user_invitations
      WHERE token_hash = p_token_hash AND status IN ('accepted', 'successful')
    ) INTO v_existing_accepted;

    IF v_existing_accepted THEN
      RETURN jsonb_build_object('ok', true, 'code', 'ALREADY_ACCEPTED', 'message', 'Invitation already accepted');
    END IF;

    RETURN jsonb_build_object('ok', false, 'code', 'INVALID_TOKEN', 'message', 'Invalid or expired invitation token');
  END IF;

  IF v_invitation.expires_at < now() THEN
    UPDATE public.user_invitations
       SET status = 'expired', updated_at = now()
     WHERE id = v_invitation.id;
    RETURN jsonb_build_object('ok', false, 'code', 'EXPIRED', 'message', 'This invitation has expired');
  END IF;

  IF v_invitation.relationship_role IS NOT NULL THEN
    v_relationship_role := v_invitation.relationship_role;
  ELSIF v_invitation.unicorn_role::text = 'Admin' THEN
    v_relationship_role := 'primary_contact';
  ELSE
    v_relationship_role := 'user';
  END IF;

  IF (v_invitation.relationship_role IS NULL
      AND v_invitation.unicorn_role::text NOT IN ('Admin','User'))
     OR v_invitation.tenant_id = 6372 THEN
    v_is_internal_fallback := true;
  END IF;

  CASE v_relationship_role
    WHEN 'primary_contact' THEN
      v_tu_role := 'parent'; v_tu_primary := true;  v_tu_secondary := false; v_tu_access_scope := 'full';
      v_u_unicorn_role := 'Admin'; v_u_user_type := 'Client Parent';
      v_tm_role := 'Admin'; v_tm_status := 'active';
    WHEN 'secondary_contact' THEN
      v_tu_role := 'parent'; v_tu_primary := false; v_tu_secondary := true;  v_tu_access_scope := 'full';
      v_u_unicorn_role := 'Admin'; v_u_user_type := 'Client Parent';
      v_tm_role := 'Admin'; v_tm_status := 'active';
    WHEN 'user' THEN
      v_tu_role := 'child';  v_tu_primary := false; v_tu_secondary := false; v_tu_access_scope := 'full';
      v_u_unicorn_role := 'User'; v_u_user_type := 'Client Child';
      v_tm_role := 'General User'; v_tm_status := 'active';
    WHEN 'academy_user' THEN
      v_tu_role := 'child';  v_tu_primary := false; v_tu_secondary := false; v_tu_access_scope := 'academy_only';
      v_u_unicorn_role := 'Academy User'; v_u_user_type := 'Client Child';
      v_tm_role := 'General User'; v_tm_status := 'inactive';
  END CASE;

  IF v_is_internal_fallback THEN
    v_u_user_type := 'Vivacity Team';
    IF v_invitation.unicorn_role IS NOT NULL THEN
      v_u_unicorn_role := v_invitation.unicorn_role::public.unicorn_role;
    END IF;
    v_tm_role := 'Admin';
    v_tm_status := 'active';
  END IF;

  SELECT user_uuid INTO v_existing_uuid
  FROM public.users
  WHERE email = lower(v_invitation.email);

  IF v_existing_uuid IS NOT NULL AND v_existing_uuid <> p_user_id THEN
    UPDATE public.users
       SET user_uuid    = p_user_id,
           first_name   = COALESCE(NULLIF(v_invitation.first_name, ''), first_name),
           last_name    = COALESCE(NULLIF(v_invitation.last_name, ''), last_name),
           unicorn_role = v_u_unicorn_role,
           user_type    = v_u_user_type,
           tenant_id    = COALESCE(tenant_id, v_invitation.tenant_id),
           is_team      = (v_u_user_type = 'Vivacity Team'),
           updated_at   = now()
     WHERE user_uuid = v_existing_uuid;
  ELSIF v_existing_uuid IS NULL THEN
    INSERT INTO public.users (
      user_uuid, email, first_name, last_name, unicorn_role, user_type,
      tenant_id, is_team, disabled, archived
    ) VALUES (
      p_user_id,
      lower(v_invitation.email),
      COALESCE(NULLIF(v_invitation.first_name, ''), '-'),
      COALESCE(NULLIF(v_invitation.last_name, ''), '-'),
      v_u_unicorn_role,
      v_u_user_type,
      v_invitation.tenant_id,
      (v_u_user_type = 'Vivacity Team'),
      false,
      false
    );
  ELSE
    UPDATE public.users
       SET first_name   = COALESCE(NULLIF(v_invitation.first_name, ''), first_name),
           last_name    = COALESCE(NULLIF(v_invitation.last_name, ''), last_name),
           unicorn_role = v_u_unicorn_role,
           user_type    = v_u_user_type,
           tenant_id    = COALESCE(tenant_id, v_invitation.tenant_id),
           updated_at   = now()
     WHERE user_uuid = p_user_id;
  END IF;

  INSERT INTO public.tenant_users (
    user_id, tenant_id, role, primary_contact, secondary_contact, access_scope, relationship_role
  ) VALUES (
    p_user_id, v_invitation.tenant_id, v_tu_role, v_tu_primary, v_tu_secondary, v_tu_access_scope, v_relationship_role
  )
  ON CONFLICT (tenant_id, user_id) DO UPDATE SET
    relationship_role = EXCLUDED.relationship_role,
    role              = EXCLUDED.role,
    primary_contact   = EXCLUDED.primary_contact,
    secondary_contact = EXCLUDED.secondary_contact,
    access_scope      = EXCLUDED.access_scope;

  INSERT INTO public.tenant_members (tenant_id, user_id, role, status)
  VALUES (v_invitation.tenant_id, p_user_id, v_tm_role, v_tm_status)
  ON CONFLICT (tenant_id, user_id) DO UPDATE SET
    role       = EXCLUDED.role,
    status     = EXCLUDED.status,
    updated_at = now();

  UPDATE public.profiles
     SET active_tenant_id = (
           SELECT id_uuid FROM public.tenants WHERE id = v_invitation.tenant_id
         ),
         updated_at = now()
   WHERE user_id = p_user_id
     AND active_tenant_id IS NULL;

  UPDATE public.user_invitations
     SET status = 'accepted',
         accepted_at = now(),
         accepted_by_user_id = p_user_id,
         updated_at = now()
   WHERE id = v_invitation.id;

  INSERT INTO public.audit_eos_events (
    tenant_id, user_id, entity, entity_id, action, reason, details
  ) VALUES (
    v_invitation.tenant_id,
    p_user_id,
    'user_invitations',
    v_invitation.id,
    'invitation_accepted',
    'User accepted invitation via self-service',
    jsonb_build_object(
      'email', v_invitation.email,
      'tenant_id', v_invitation.tenant_id,
      'unicorn_role', v_u_unicorn_role::text,
      'user_type', v_u_user_type::text,
      'tenant_users_role', v_tu_role,
      'primary_contact', v_tu_primary,
      'secondary_contact', v_tu_secondary,
      'access_scope', v_tu_access_scope,
      'relationship_role', v_relationship_role::text,
      'tm_role', v_tm_role,
      'tm_status', v_tm_status,
      'invitation_relationship_role_source', CASE WHEN v_invitation.relationship_role IS NOT NULL THEN 'invitation_column' ELSE 'unicorn_role_fallback' END,
      'internal_fallback', v_is_internal_fallback,
      'invitation_id', v_invitation.id,
      'relinked_from_uuid', CASE WHEN v_existing_uuid IS NOT NULL AND v_existing_uuid <> p_user_id
                                 THEN v_existing_uuid::text ELSE NULL END
    )
  );

  RETURN jsonb_build_object(
    'ok', true,
    'code', 'SUCCESS',
    'tenant_id', v_invitation.tenant_id,
    'role', v_tu_role,
    'unicorn_role', v_u_unicorn_role::text,
    'primary_contact', v_tu_primary,
    'secondary_contact', v_tu_secondary,
    'access_scope', v_tu_access_scope,
    'relationship_role', v_relationship_role::text,
    'message', 'Invitation accepted successfully'
  );
END;
$function$;

-- 7.2 set_relationship_role
CREATE OR REPLACE FUNCTION public.set_relationship_role(p_tenant_id bigint, p_user_id uuid, p_relationship_role tenant_user_role, p_reason text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_caller uuid := auth.uid();
  v_is_staff boolean := false;
  v_is_tenant_admin boolean := false;
  v_tu_id bigint;
  v_old_role public.tenant_user_role;
  v_tu_role text;
  v_tu_primary boolean;
  v_tu_secondary boolean;
  v_tu_access_scope text;
  v_u_unicorn_role public.unicorn_role;
  v_u_user_type text;
  v_tm_role text;
  v_tm_status text;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '42501';
  END IF;

  IF p_tenant_id IS NULL OR p_user_id IS NULL OR p_relationship_role IS NULL THEN
    RAISE EXCEPTION 'set_relationship_role: missing required parameters';
  END IF;

  v_is_staff := public.is_super_admin_safe(v_caller) OR public.is_vivacity_team_safe(v_caller);

  IF NOT v_is_staff THEN
    SELECT EXISTS (
      SELECT 1 FROM public.tenant_users
      WHERE tenant_id = p_tenant_id
        AND user_id = v_caller
        AND relationship_role IN ('primary_contact','secondary_contact')
        AND access_scope = 'full'
    ) INTO v_is_tenant_admin;

    IF NOT v_is_tenant_admin THEN
      RAISE EXCEPTION 'Not authorized to change roles for tenant %', p_tenant_id
        USING ERRCODE = '42501';
    END IF;
  END IF;

  CASE p_relationship_role
    WHEN 'primary_contact' THEN
      v_tu_role := 'parent'; v_tu_primary := true;  v_tu_secondary := false; v_tu_access_scope := 'full';
      v_u_unicorn_role := 'Admin'; v_u_user_type := 'Client Parent';
      v_tm_role := 'Admin'; v_tm_status := 'active';
    WHEN 'secondary_contact' THEN
      v_tu_role := 'parent'; v_tu_primary := false; v_tu_secondary := true;  v_tu_access_scope := 'full';
      v_u_unicorn_role := 'Admin'; v_u_user_type := 'Client Parent';
      v_tm_role := 'Admin'; v_tm_status := 'active';
    WHEN 'user' THEN
      v_tu_role := 'child';  v_tu_primary := false; v_tu_secondary := false; v_tu_access_scope := 'full';
      v_u_unicorn_role := 'User'; v_u_user_type := 'Client Child';
      v_tm_role := 'General User'; v_tm_status := 'active';
    WHEN 'academy_user' THEN
      v_tu_role := 'child';  v_tu_primary := false; v_tu_secondary := false; v_tu_access_scope := 'academy_only';
      v_u_unicorn_role := 'Academy User'; v_u_user_type := 'Client Child';
      v_tm_role := 'General User'; v_tm_status := 'inactive';
    ELSE
      RAISE EXCEPTION 'Unsupported relationship_role %', p_relationship_role;
  END CASE;

  SELECT id, relationship_role
    INTO v_tu_id, v_old_role
  FROM public.tenant_users
  WHERE tenant_id = p_tenant_id AND user_id = p_user_id;

  IF v_tu_id IS NULL THEN
    RAISE EXCEPTION 'tenant_users row not found for tenant=% user=%', p_tenant_id, p_user_id;
  END IF;

  UPDATE public.tenant_users
     SET relationship_role = p_relationship_role,
         role              = v_tu_role,
         primary_contact   = v_tu_primary,
         secondary_contact = v_tu_secondary,
         access_scope      = v_tu_access_scope
   WHERE tenant_id = p_tenant_id AND user_id = p_user_id;

  UPDATE public.users
     SET unicorn_role = v_u_unicorn_role,
         user_type    = v_u_user_type,
         updated_at   = now()
   WHERE user_uuid = p_user_id;

  INSERT INTO public.tenant_members (tenant_id, user_id, role, status)
  VALUES (p_tenant_id, p_user_id, v_tm_role, v_tm_status)
  ON CONFLICT (tenant_id, user_id) DO UPDATE
    SET role       = EXCLUDED.role,
        status     = EXCLUDED.status,
        updated_at = now();

  INSERT INTO public.audit_eos_events (
    tenant_id, user_id, entity, entity_id, action, reason, details
  ) VALUES (
    p_tenant_id,
    p_user_id,
    'tenant_users',
    NULL,
    'relationship_role_changed',
    p_reason,
    jsonb_build_object(
      'tu_id', v_tu_id,
      'old_relationship_role', v_old_role::text,
      'new_relationship_role', p_relationship_role::text,
      'tu_role', v_tu_role,
      'tu_primary_contact', v_tu_primary,
      'tu_secondary_contact', v_tu_secondary,
      'tu_access_scope', v_tu_access_scope,
      'tm_role', v_tm_role,
      'tm_status', v_tm_status,
      'changed_by', v_caller
    )
  );

  RETURN jsonb_build_object(
    'ok', true,
    'tenant_id', p_tenant_id,
    'user_id', p_user_id,
    'relationship_role', p_relationship_role::text,
    'access_scope', v_tu_access_scope,
    'tm_status', v_tm_status
  );
END;
$function$;

-- 7.3 handle_new_user
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF EXISTS (SELECT 1 FROM public.users WHERE LOWER(email) = LOWER(NEW.email)) THEN
    UPDATE public.users
    SET user_uuid = NEW.id,
        updated_at = now()
    WHERE LOWER(email) = LOWER(NEW.email);
  ELSIF NOT EXISTS (SELECT 1 FROM public.users WHERE user_uuid = NEW.id) THEN
    INSERT INTO public.users (
      user_uuid, email, first_name, last_name, unicorn_role, user_type,
      tenant_id, phone, created_at, updated_at
    ) VALUES (
      NEW.id, NEW.email,
      COALESCE(NEW.raw_user_meta_data->>'first_name', ''),
      COALESCE(NEW.raw_user_meta_data->>'last_name', ''),
      COALESCE((NEW.raw_user_meta_data->>'unicorn_role')::unicorn_role, 'User'::unicorn_role),
      COALESCE(NEW.raw_user_meta_data->>'user_type', 'Member'),
      COALESCE((NEW.raw_user_meta_data->>'tenant_id')::bigint, NULL),
      COALESCE(NEW.raw_user_meta_data->>'phone', NULL),
      now(), now()
    );
  END IF;
  
  RETURN NEW;
END;
$function$;

-- 7.4 admin_set_role_type
CREATE OR REPLACE FUNCTION public.admin_set_role_type(p_user_uuid uuid, p_role_type text, p_tenant_id bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  v_unicorn_role text;
  v_user_type text;
  v_old_data jsonb;
  v_new_data jsonb;
BEGIN
  IF NOT public.is_super_admin() THEN
    RAISE EXCEPTION 'Access denied: SuperAdmin only';
  END IF;

  CASE p_role_type
    WHEN 'superadmin_administrator' THEN
      v_unicorn_role := 'Super Admin';
      v_user_type := 'Vivacity';
    WHEN 'superadmin_team_leader' THEN
      v_unicorn_role := 'Super Admin';
      v_user_type := 'Vivacity Team';
    WHEN 'superadmin_general' THEN
      v_unicorn_role := 'User';
      v_user_type := 'Vivacity Team';
    WHEN 'tenant_parent' THEN
      v_unicorn_role := 'Admin';
      v_user_type := 'Client Parent';
    WHEN 'tenant_child' THEN
      v_unicorn_role := 'User';
      v_user_type := 'Client Child';
    ELSE
      RAISE EXCEPTION 'Invalid role_type: %', p_role_type;
  END CASE;

  SELECT jsonb_build_object(
    'unicorn_role', unicorn_role,
    'user_type', user_type,
    'tenant_id', tenant_id
  ) INTO v_old_data
  FROM public.users
  WHERE user_uuid = p_user_uuid;

  UPDATE public.users
  SET 
    unicorn_role = v_unicorn_role::public.unicorn_role,
    user_type = v_user_type,
    tenant_id = CASE 
      WHEN p_role_type LIKE 'superadmin_%' THEN 319
      ELSE p_tenant_id
    END,
    updated_at = now()
  WHERE user_uuid = p_user_uuid;

  v_new_data := jsonb_build_object(
    'unicorn_role', v_unicorn_role,
    'user_type', v_user_type,
    'tenant_id', CASE WHEN p_role_type LIKE 'superadmin_%' THEN 319 ELSE p_tenant_id END
  );

  INSERT INTO public.audit_eos_events (
    tenant_id, entity, action, entity_id, user_id, details
  ) VALUES (
    319,
    'user_audit',
    'set_role_type',
    p_user_uuid::text,
    auth.uid(),
    jsonb_build_object('before', v_old_data, 'after', v_new_data, 'role_type', p_role_type)
  );

  RETURN jsonb_build_object(
    'success', true,
    'user_uuid', p_user_uuid,
    'role_type', p_role_type,
    'before', v_old_data,
    'after', v_new_data
  );
END;
$function$;

-- ---------------------------------------------------------------------
-- STEP 8 — COMMENT ON LEGACY ENUM (retain, do not drop)
-- ---------------------------------------------------------------------
COMMENT ON TYPE public.user_type_enum IS
  'DEPRECATED 2026-05: replaced by public.dd_user_type lookup table. '
  'Retained because archive.backup_users still references this type. '
  'Do not drop until archive.backup_users is removed in the separate '
  'cleanup migration. Do not add new columns of this type.';

-- ---------------------------------------------------------------------
-- STEP 9 — POST-FLIGHT VERIFICATION ASSERTIONS
-- ---------------------------------------------------------------------
DO $postflight$
DECLARE
  v_lookup_count   bigint;
  v_nulls          bigint;
  v_unresolved     bigint;
  v_client_parent  bigint;
  v_client_child   bigint;
  v_vivacity_team  bigint;
  v_vivacity       bigint;
  v_client         bigint;
  v_member         bigint;
  v_col_type       text;
  v_col_nullable   text;
  v_fk_def         text;
  v_bad_policies   bigint;
  v_policy_count   bigint;
  v_bad_funcs      bigint;
  v_enum_present   bigint;
BEGIN
  SELECT count(*) INTO v_lookup_count FROM public.dd_user_type;
  IF v_lookup_count <> 6 THEN
    RAISE EXCEPTION 'POST-FLIGHT FAIL: dd_user_type row count = %, expected 6', v_lookup_count;
  END IF;

  SELECT count(*) INTO v_nulls FROM public.users WHERE user_type IS NULL;
  IF v_nulls <> 0 THEN
    RAISE EXCEPTION 'POST-FLIGHT FAIL: % users have NULL user_type', v_nulls;
  END IF;

  SELECT count(*) INTO v_unresolved
  FROM public.users u
  LEFT JOIN public.dd_user_type d ON d.value = u.user_type
  WHERE d.value IS NULL;
  IF v_unresolved <> 0 THEN
    RAISE EXCEPTION 'POST-FLIGHT FAIL: % users do not resolve through dd_user_type FK', v_unresolved;
  END IF;

  SELECT
    count(*) FILTER (WHERE user_type = 'Client Parent'),
    count(*) FILTER (WHERE user_type = 'Client Child'),
    count(*) FILTER (WHERE user_type = 'Vivacity Team'),
    count(*) FILTER (WHERE user_type = 'Vivacity'),
    count(*) FILTER (WHERE user_type = 'Client'),
    count(*) FILTER (WHERE user_type = 'Member')
  INTO v_client_parent, v_client_child, v_vivacity_team,
       v_vivacity,      v_client,       v_member
  FROM public.users;

  IF v_client_parent <> 417 OR v_client_child <> 62 OR v_vivacity_team <> 23
     OR v_vivacity <> 0 OR v_client <> 0 OR v_member <> 0 THEN
    RAISE EXCEPTION 'POST-FLIGHT FAIL: distribution changed (CP=%, CC=%, VT=%, V=%, C=%, M=%)',
      v_client_parent, v_client_child, v_vivacity_team, v_vivacity, v_client, v_member;
  END IF;

  SELECT data_type, is_nullable INTO v_col_type, v_col_nullable
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'user_type';
  IF v_col_type <> 'text' OR v_col_nullable <> 'NO' THEN
    RAISE EXCEPTION 'POST-FLIGHT FAIL: users.user_type is (type=%, nullable=%), expected (text, NO)',
      v_col_type, v_col_nullable;
  END IF;

  SELECT pg_get_constraintdef(c.oid) INTO v_fk_def
  FROM pg_constraint c
  WHERE c.conname = 'users_user_type_fkey'
    AND c.conrelid = 'public.users'::regclass;
  IF v_fk_def IS NULL
     OR v_fk_def NOT ILIKE '%REFERENCES%dd_user_type(value)%'
     OR v_fk_def NOT ILIKE '%ON UPDATE CASCADE%'
     OR v_fk_def NOT ILIKE '%ON DELETE RESTRICT%' THEN
    RAISE EXCEPTION 'POST-FLIGHT FAIL: users_user_type_fkey definition unexpected: %', v_fk_def;
  END IF;

  SELECT count(*) INTO v_policy_count
  FROM pg_policies
  WHERE schemaname='public' AND policyname IN (
    'tasks_tenants_tenant_select',
    'tasks_tenants_tenant_update',
    'eos_agenda_template_versions_admin_insert',
    'eos_agenda_template_versions_admin_update');
  IF v_policy_count <> 4 THEN
    RAISE EXCEPTION 'POST-FLIGHT FAIL: expected 4 rewritten policies, found %', v_policy_count;
  END IF;

  SELECT count(*) INTO v_bad_policies
  FROM pg_policies
  WHERE schemaname = 'public'
    AND policyname IN (
      'tasks_tenants_tenant_select',
      'tasks_tenants_tenant_update',
      'eos_agenda_template_versions_admin_insert',
      'eos_agenda_template_versions_admin_update'
    )
    AND (
      COALESCE(qual, '')        ILIKE '%user_type_enum%' OR
      COALESCE(with_check, '')  ILIKE '%user_type_enum%'
    );
  IF v_bad_policies <> 0 THEN
    RAISE EXCEPTION 'POST-FLIGHT FAIL: % rewritten policies still mention user_type_enum', v_bad_policies;
  END IF;

  SELECT count(*) INTO v_bad_funcs
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public'
    AND p.proname IN ('accept_invitation_v2','set_relationship_role','handle_new_user','admin_set_role_type')
    AND p.prosrc ILIKE '%user_type_enum%';
  IF v_bad_funcs <> 0 THEN
    RAISE EXCEPTION 'POST-FLIGHT FAIL: % updated functions still reference user_type_enum', v_bad_funcs;
  END IF;

  SELECT count(*) INTO v_enum_present
  FROM pg_type t
  JOIN pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'public' AND t.typname = 'user_type_enum';
  IF v_enum_present <> 1 THEN
    RAISE EXCEPTION 'POST-FLIGHT FAIL: public.user_type_enum was unexpectedly removed';
  END IF;

  RAISE NOTICE 'POST-FLIGHT PASSED. Migration complete.';
END
$postflight$;

-- =====================================================================
-- STEP 10 — ROLLBACK SQL (DO NOT RUN as part of this migration)
-- =====================================================================
-- Run manually, in order, only if rollback is required. The 4 policies
-- must again be dropped BEFORE the column type is reverted to enum.
--
-- -- 10.1 Restore the 4 functions (re-add ::user_type_enum declarations / casts)
-- --      Re-run the prior CREATE OR REPLACE bodies for:
-- --        public.accept_invitation_v2   (DECLARE v_u_user_type public.user_type_enum;)
-- --        public.set_relationship_role  (DECLARE v_u_user_type public.user_type_enum;)
-- --        public.handle_new_user        (COALESCE((... ->>'user_type')::user_type_enum, 'Member'::user_type_enum))
-- --        public.admin_set_role_type    (SET user_type = v_user_type::public.user_type_enum)
--
-- -- 10.2 Drop the 4 (now text-based) RLS policies
-- DROP POLICY IF EXISTS tasks_tenants_tenant_select ON public.tasks_tenants;
-- DROP POLICY IF EXISTS tasks_tenants_tenant_update ON public.tasks_tenants;
-- DROP POLICY IF EXISTS eos_agenda_template_versions_admin_insert ON public.eos_agenda_template_versions;
-- DROP POLICY IF EXISTS eos_agenda_template_versions_admin_update ON public.eos_agenda_template_versions;
--
-- -- 10.3 Drop FK + index
-- ALTER TABLE public.users DROP CONSTRAINT users_user_type_fkey;
-- DROP INDEX IF EXISTS public.idx_users_user_type;
--
-- -- 10.4 Convert column back to enum (safe — values unchanged)
-- ALTER TABLE public.users
--   ALTER COLUMN user_type TYPE public.user_type_enum
--   USING user_type::public.user_type_enum;
--
-- -- 10.5 Re-create the 4 policies with ::user_type_enum casts on ARRAY literals
-- CREATE POLICY tasks_tenants_tenant_select ON public.tasks_tenants
--   FOR SELECT TO authenticated
--   USING (
--     (tenant_id = (SELECT users.tenant_id FROM users WHERE users.user_uuid = (SELECT auth.uid())))
--     AND ((SELECT users.user_type FROM users WHERE users.user_uuid = (SELECT auth.uid())) = ANY (ARRAY['Client Parent'::user_type_enum, 'Client Child'::user_type_enum]))
--   );
-- CREATE POLICY tasks_tenants_tenant_update ON public.tasks_tenants
--   FOR UPDATE TO authenticated
--   USING (
--     (tenant_id = (SELECT users.tenant_id FROM users WHERE users.user_uuid = (SELECT auth.uid())))
--     AND ((SELECT users.user_type FROM users WHERE users.user_uuid = (SELECT auth.uid())) = ANY (ARRAY['Client Parent'::user_type_enum, 'Client Child'::user_type_enum]))
--   )
--   WITH CHECK (
--     (tenant_id = (SELECT users.tenant_id FROM users WHERE users.user_uuid = (SELECT auth.uid())))
--     AND ((SELECT users.user_type FROM users WHERE users.user_uuid = (SELECT auth.uid())) = ANY (ARRAY['Client Parent'::user_type_enum, 'Client Child'::user_type_enum]))
--   );
-- CREATE POLICY eos_agenda_template_versions_admin_insert ON public.eos_agenda_template_versions
--   FOR INSERT TO public
--   WITH CHECK (
--     is_super_admin() OR (EXISTS (
--       SELECT 1 FROM eos_agenda_templates t
--       JOIN users u ON u.tenant_id = t.tenant_id
--       WHERE t.id = eos_agenda_template_versions.template_id
--         AND u.user_uuid = (SELECT auth.uid())
--         AND u.user_type = ANY (ARRAY['Vivacity'::user_type_enum, 'Client'::user_type_enum, 'Vivacity Team'::user_type_enum])
--     ))
--   );
-- CREATE POLICY eos_agenda_template_versions_admin_update ON public.eos_agenda_template_versions
--   FOR UPDATE TO public
--   USING (
--     is_super_admin() OR (EXISTS (
--       SELECT 1 FROM eos_agenda_templates t
--       JOIN users u ON u.tenant_id = t.tenant_id
--       WHERE t.id = eos_agenda_template_versions.template_id
--         AND u.user_uuid = (SELECT auth.uid())
--         AND u.user_type = ANY (ARRAY['Vivacity'::user_type_enum, 'Client'::user_type_enum, 'Vivacity Team'::user_type_enum])
--     ))
--   );
--
-- -- 10.6 Drop lookup RLS + table
-- ALTER TABLE public.dd_user_type DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS dd_user_type_read ON public.dd_user_type;
-- DROP TABLE public.dd_user_type;
--
-- -- 10.7 Clear deprecation comment
-- COMMENT ON TYPE public.user_type_enum IS NULL;
